// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/action/index.js (order kept)
import I0 from '$lib/icons/16/action/AddLarge16.svelte';
import I1 from '$lib/icons/16/action/AddSmall16.svelte';
import I2 from '$lib/icons/16/action/Arrow16.svelte';
import I3 from '$lib/icons/16/action/Attachment16.svelte';
import I4 from '$lib/icons/16/action/AttachmentLink16.svelte';
import I5 from '$lib/icons/16/action/AttachmentLinkAdd16.svelte';
import I6 from '$lib/icons/16/action/AttachmentLinkBreak16.svelte';
import I7 from '$lib/icons/16/action/Attention16.svelte';
import I8 from '$lib/icons/16/action/AttentionMark16.svelte';
import I9 from '$lib/icons/16/action/Backspace16.svelte';
import I10 from '$lib/icons/16/action/BackspaceFill16.svelte';
import I11 from '$lib/icons/16/action/BarCode16.svelte';
import I12 from '$lib/icons/16/action/BarID16.svelte';
import I13 from '$lib/icons/16/action/BlockAdd16.svelte';
import I14 from '$lib/icons/16/action/Catalog16.svelte';
import I15 from '$lib/icons/16/action/CatalogAdd16.svelte';
import I16 from '$lib/icons/16/action/CheckEdit16.svelte';
import I17 from '$lib/icons/16/action/CheckStatistics16.svelte';
import I18 from '$lib/icons/16/action/Checklist16.svelte';
import I19 from '$lib/icons/16/action/CloudDownload16.svelte';
import I20 from '$lib/icons/16/action/CloudUpload16.svelte';
import I21 from '$lib/icons/16/action/Copy16.svelte';
import I22 from '$lib/icons/16/action/Download16.svelte';
import I23 from '$lib/icons/16/action/Empty16.svelte';
import I24 from '$lib/icons/16/action/Equaliser16.svelte';
import I25 from '$lib/icons/16/action/EqualiserLear16.svelte';
import I26 from '$lib/icons/16/action/FaceID16.svelte';
import I27 from '$lib/icons/16/action/Filter16.svelte';
import I28 from '$lib/icons/16/action/FilterAdd16.svelte';
import I29 from '$lib/icons/16/action/FilterClear16.svelte';
import I30 from '$lib/icons/16/action/FilterFill16.svelte';
import I31 from '$lib/icons/16/action/GalleryCards16.svelte';
import I32 from '$lib/icons/16/action/HeartList16.svelte';
import I33 from '$lib/icons/16/action/Home16.svelte';
import I34 from '$lib/icons/16/action/ImageRotation16.svelte';
import I35 from '$lib/icons/16/action/KeyOld16.svelte';
import I36 from '$lib/icons/16/action/KeyPassword16.svelte';
import I37 from '$lib/icons/16/action/Link16.svelte';
import I38 from '$lib/icons/16/action/Lock16.svelte';
import I39 from '$lib/icons/16/action/LockAdd16.svelte';
import I40 from '$lib/icons/16/action/Mouse16.svelte';
import I41 from '$lib/icons/16/action/Notification16.svelte';
import I42 from '$lib/icons/16/action/NotificationNew16.svelte';
import I43 from '$lib/icons/16/action/NotificationOff16.svelte';
import I44 from '$lib/icons/16/action/ObjectRotation16.svelte';
import I45 from '$lib/icons/16/action/PIN16.svelte';
import I46 from '$lib/icons/16/action/Password16.svelte';
import I47 from '$lib/icons/16/action/PasswordHide16.svelte';
import I48 from '$lib/icons/16/action/PasswordShow16.svelte';
import I49 from '$lib/icons/16/action/Pointer16.svelte';
import I50 from '$lib/icons/16/action/Print16.svelte';
import I51 from '$lib/icons/16/action/ProgressDownload16.svelte';
import I52 from '$lib/icons/16/action/PushPin16.svelte';
import I53 from '$lib/icons/16/action/PushPinFill16.svelte';
import I54 from '$lib/icons/16/action/PushPinOff16.svelte';
import I55 from '$lib/icons/16/action/PushPinOffFill16.svelte';
import I56 from '$lib/icons/16/action/QRCode16.svelte';
import I57 from '$lib/icons/16/action/QRID16.svelte';
import I58 from '$lib/icons/16/action/Reboot16.svelte';
import I59 from '$lib/icons/16/action/Refresh16.svelte';
import I60 from '$lib/icons/16/action/RefreshSmall16.svelte';
import I61 from '$lib/icons/16/action/Release16.svelte';
import I62 from '$lib/icons/16/action/RemoveLarge16.svelte';
import I63 from '$lib/icons/16/action/RemoveSmall16.svelte';
import I64 from '$lib/icons/16/action/SOS16.svelte';
import I65 from '$lib/icons/16/action/Search16.svelte';
import I66 from '$lib/icons/16/action/Security16.svelte';
import I67 from '$lib/icons/16/action/SecurityCheck16.svelte';
import I68 from '$lib/icons/16/action/SecurityHealth16.svelte';
import I69 from '$lib/icons/16/action/SecurityRules16.svelte';
import I70 from '$lib/icons/16/action/Send16.svelte';
import I71 from '$lib/icons/16/action/Settings16.svelte';
import I72 from '$lib/icons/16/action/SettingsAdjust16.svelte';
import I73 from '$lib/icons/16/action/SwitchOff16.svelte';
import I74 from '$lib/icons/16/action/SwitchOn16.svelte';
import I75 from '$lib/icons/16/action/Synchronization16.svelte';
import I76 from '$lib/icons/16/action/SynchronizationSmall16.svelte';
import I77 from '$lib/icons/16/action/TouchID16.svelte';
import I78 from '$lib/icons/16/action/Trash16.svelte';
import I79 from '$lib/icons/16/action/Unlock16.svelte';
import I80 from '$lib/icons/16/action/Upload16.svelte';

export default {
	"AddLarge16": I0,
	"AddSmall16": I1,
	"Arrow16": I2,
	"Attachment16": I3,
	"AttachmentLink16": I4,
	"AttachmentLinkAdd16": I5,
	"AttachmentLinkBreak16": I6,
	"Attention16": I7,
	"AttentionMark16": I8,
	"Backspace16": I9,
	"BackspaceFill16": I10,
	"BarCode16": I11,
	"BarID16": I12,
	"BlockAdd16": I13,
	"Catalog16": I14,
	"CatalogAdd16": I15,
	"CheckEdit16": I16,
	"CheckStatistics16": I17,
	"Checklist16": I18,
	"CloudDownload16": I19,
	"CloudUpload16": I20,
	"Copy16": I21,
	"Download16": I22,
	"Empty16": I23,
	"Equaliser16": I24,
	"EqualiserLear16": I25,
	"FaceID16": I26,
	"Filter16": I27,
	"FilterAdd16": I28,
	"FilterClear16": I29,
	"FilterFill16": I30,
	"GalleryCards16": I31,
	"HeartList16": I32,
	"Home16": I33,
	"ImageRotation16": I34,
	"KeyOld16": I35,
	"KeyPassword16": I36,
	"Link16": I37,
	"Lock16": I38,
	"LockAdd16": I39,
	"Mouse16": I40,
	"Notification16": I41,
	"NotificationNew16": I42,
	"NotificationOff16": I43,
	"ObjectRotation16": I44,
	"PIN16": I45,
	"Password16": I46,
	"PasswordHide16": I47,
	"PasswordShow16": I48,
	"Pointer16": I49,
	"Print16": I50,
	"ProgressDownload16": I51,
	"PushPin16": I52,
	"PushPinFill16": I53,
	"PushPinOff16": I54,
	"PushPinOffFill16": I55,
	"QRCode16": I56,
	"QRID16": I57,
	"Reboot16": I58,
	"Refresh16": I59,
	"RefreshSmall16": I60,
	"Release16": I61,
	"RemoveLarge16": I62,
	"RemoveSmall16": I63,
	"SOS16": I64,
	"Search16": I65,
	"Security16": I66,
	"SecurityCheck16": I67,
	"SecurityHealth16": I68,
	"SecurityRules16": I69,
	"Send16": I70,
	"Settings16": I71,
	"SettingsAdjust16": I72,
	"SwitchOff16": I73,
	"SwitchOn16": I74,
	"Synchronization16": I75,
	"SynchronizationSmall16": I76,
	"TouchID16": I77,
	"Trash16": I78,
	"Unlock16": I79,
	"Upload16": I80
};
