// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/alert/index.js (order kept)
import I0 from '$lib/icons/16/alert/AttentionColor16.svelte';
import I1 from '$lib/icons/16/alert/AttentionMonochrome16.svelte';
import I2 from '$lib/icons/16/alert/AttentionStroke16.svelte';
import I3 from '$lib/icons/16/alert/ErrorColor16.svelte';
import I4 from '$lib/icons/16/alert/ErrorMonochrome16.svelte';
import I5 from '$lib/icons/16/alert/ErrorStroke16.svelte';
import I6 from '$lib/icons/16/alert/HelpColor16.svelte';
import I7 from '$lib/icons/16/alert/HelpMonochrome16.svelte';
import I8 from '$lib/icons/16/alert/HelpStroke16.svelte';
import I9 from '$lib/icons/16/alert/InformationColor16.svelte';
import I10 from '$lib/icons/16/alert/InformationMonochrome16.svelte';
import I11 from '$lib/icons/16/alert/InformationStroke16.svelte';
import I12 from '$lib/icons/16/alert/NoneColor16.svelte';
import I13 from '$lib/icons/16/alert/NoneMonochrome16.svelte';
import I14 from '$lib/icons/16/alert/NoneStroke16.svelte';
import I15 from '$lib/icons/16/alert/OkColor16.svelte';
import I16 from '$lib/icons/16/alert/OkMonochrome16.svelte';
import I17 from '$lib/icons/16/alert/OkStroke16.svelte';
import I18 from '$lib/icons/16/alert/SkipColor16.svelte';
import I19 from '$lib/icons/16/alert/SkipMonochrome16.svelte';
import I20 from '$lib/icons/16/alert/SkipStroke16.svelte';
import I21 from '$lib/icons/16/alert/StopColor16.svelte';
import I22 from '$lib/icons/16/alert/StopMonochrome16.svelte';
import I23 from '$lib/icons/16/alert/StopStroke16.svelte';
import I24 from '$lib/icons/16/alert/TimeColor16.svelte';
import I25 from '$lib/icons/16/alert/TimeMonochrome16.svelte';
import I26 from '$lib/icons/16/alert/TimeStroke16.svelte';

export default {
	"AttentionColor16": I0,
	"AttentionMonochrome16": I1,
	"AttentionStroke16": I2,
	"ErrorColor16": I3,
	"ErrorMonochrome16": I4,
	"ErrorStroke16": I5,
	"HelpColor16": I6,
	"HelpMonochrome16": I7,
	"HelpStroke16": I8,
	"InformationColor16": I9,
	"InformationMonochrome16": I10,
	"InformationStroke16": I11,
	"NoneColor16": I12,
	"NoneMonochrome16": I13,
	"NoneStroke16": I14,
	"OkColor16": I15,
	"OkMonochrome16": I16,
	"OkStroke16": I17,
	"SkipColor16": I18,
	"SkipMonochrome16": I19,
	"SkipStroke16": I20,
	"StopColor16": I21,
	"StopMonochrome16": I22,
	"StopStroke16": I23,
	"TimeColor16": I24,
	"TimeMonochrome16": I25,
	"TimeStroke16": I26
};
