// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/business/index.js (order kept)
import I0 from '$lib/icons/16/business/DeliveryBox16.svelte';
import I1 from '$lib/icons/16/business/Group16.svelte';
import I2 from '$lib/icons/16/business/Percentage16.svelte';
import I3 from '$lib/icons/16/business/Portfolio16.svelte';
import I4 from '$lib/icons/16/business/Promocode16.svelte';
import I5 from '$lib/icons/16/business/Reuse16.svelte';
import I6 from '$lib/icons/16/business/Ruble16.svelte';
import I7 from '$lib/icons/16/business/StatisticsColumn16.svelte';
import I8 from '$lib/icons/16/business/StatisticsLine16.svelte';
import I9 from '$lib/icons/16/business/Sticker16.svelte';
import I10 from '$lib/icons/16/business/Wallet16.svelte';

export default {
	"DeliveryBox16": I0,
	"Group16": I1,
	"Percentage16": I2,
	"Portfolio16": I3,
	"Promocode16": I4,
	"Reuse16": I5,
	"Ruble16": I6,
	"StatisticsColumn16": I7,
	"StatisticsLine16": I8,
	"Sticker16": I9,
	"Wallet16": I10
};
