// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/culture/index.js (order kept)
import I0 from '$lib/icons/16/culture/Education16.svelte';

export default {
	"Education16": I0
};
