// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/communication/index.js (order kept)
import I0 from '$lib/icons/16/communication/At16.svelte';
import I1 from '$lib/icons/16/communication/Calendar16.svelte';
import I2 from '$lib/icons/16/communication/Call16.svelte';
import I3 from '$lib/icons/16/communication/CallDialog16.svelte';
import I4 from '$lib/icons/16/communication/CallEnd16.svelte';
import I5 from '$lib/icons/16/communication/CallIncoming16.svelte';
import I6 from '$lib/icons/16/communication/CallNocoming16.svelte';
import I7 from '$lib/icons/16/communication/CallOutgoing16.svelte';
import I8 from '$lib/icons/16/communication/Chat16.svelte';
import I9 from '$lib/icons/16/communication/ChatNew16.svelte';
import I10 from '$lib/icons/16/communication/Comments16.svelte';
import I11 from '$lib/icons/16/communication/CommentsNew16.svelte';
import I12 from '$lib/icons/16/communication/Connect16.svelte';
import I13 from '$lib/icons/16/communication/Contacts16.svelte';
import I14 from '$lib/icons/16/communication/Forward16.svelte';
import I15 from '$lib/icons/16/communication/ForwardFill16.svelte';
import I16 from '$lib/icons/16/communication/History16.svelte';
import I17 from '$lib/icons/16/communication/Lego16.svelte';
import I18 from '$lib/icons/16/communication/Mail16.svelte';
import I19 from '$lib/icons/16/communication/MailIncoming16.svelte';
import I20 from '$lib/icons/16/communication/MailNew16.svelte';
import I21 from '$lib/icons/16/communication/MailOpen16.svelte';
import I22 from '$lib/icons/16/communication/MailOutgoing16.svelte';
import I23 from '$lib/icons/16/communication/OperatorSupport16.svelte';
import I24 from '$lib/icons/16/communication/ParentIssue16.svelte';
import I25 from '$lib/icons/16/communication/ParentIssueDocuments16.svelte';
import I26 from '$lib/icons/16/communication/ParentIssueDouble16.svelte';
import I27 from '$lib/icons/16/communication/PeopleWait16.svelte';
import I28 from '$lib/icons/16/communication/Profile16.svelte';
import I29 from '$lib/icons/16/communication/Reply16.svelte';
import I30 from '$lib/icons/16/communication/ReplyFill16.svelte';
import I31 from '$lib/icons/16/communication/Share16.svelte';
import I32 from '$lib/icons/16/communication/Task16.svelte';
import I33 from '$lib/icons/16/communication/User16.svelte';
import I34 from '$lib/icons/16/communication/UserAdd16.svelte';
import I35 from '$lib/icons/16/communication/Users16.svelte';

export default {
	"At16": I0,
	"Calendar16": I1,
	"Call16": I2,
	"CallDialog16": I3,
	"CallEnd16": I4,
	"CallIncoming16": I5,
	"CallNocoming16": I6,
	"CallOutgoing16": I7,
	"Chat16": I8,
	"ChatNew16": I9,
	"Comments16": I10,
	"CommentsNew16": I11,
	"Connect16": I12,
	"Contacts16": I13,
	"Forward16": I14,
	"ForwardFill16": I15,
	"History16": I16,
	"Lego16": I17,
	"Mail16": I18,
	"MailIncoming16": I19,
	"MailNew16": I20,
	"MailOpen16": I21,
	"MailOutgoing16": I22,
	"OperatorSupport16": I23,
	"ParentIssue16": I24,
	"ParentIssueDocuments16": I25,
	"ParentIssueDouble16": I26,
	"PeopleWait16": I27,
	"Profile16": I28,
	"Reply16": I29,
	"ReplyFill16": I30,
	"Share16": I31,
	"Task16": I32,
	"User16": I33,
	"UserAdd16": I34,
	"Users16": I35
};
