// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/document/index.js (order kept)
import I0 from '$lib/icons/16/document/DocumentArchived16.svelte';
import I1 from '$lib/icons/16/document/DocumentEdit16.svelte';
import I2 from '$lib/icons/16/document/DocumentImage16.svelte';
import I3 from '$lib/icons/16/document/DocumentText16.svelte';
import I4 from '$lib/icons/16/document/Folder16.svelte';
import I5 from '$lib/icons/16/document/FolderFill16.svelte';
import I6 from '$lib/icons/16/document/FolderOpen16.svelte';
import I7 from '$lib/icons/16/document/FolderOpenFill16.svelte';
import I8 from '$lib/icons/16/document/Media16.svelte';
import I9 from '$lib/icons/16/document/Music16.svelte';
import I10 from '$lib/icons/16/document/Snippet16.svelte';

export default {
	"DocumentArchived16": I0,
	"DocumentEdit16": I1,
	"DocumentImage16": I2,
	"DocumentText16": I3,
	"Folder16": I4,
	"FolderFill16": I5,
	"FolderOpen16": I6,
	"FolderOpenFill16": I7,
	"Media16": I8,
	"Music16": I9,
	"Snippet16": I10
};
