// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/editor/index.js (order kept)
import I0 from '$lib/icons/16/editor/Array16.svelte';
import I1 from '$lib/icons/16/editor/Bullet16.svelte';
import I2 from '$lib/icons/16/editor/CellsMerge16.svelte';
import I3 from '$lib/icons/16/editor/Checkbox16.svelte';
import I4 from '$lib/icons/16/editor/CheckboxGroup16.svelte';
import I5 from '$lib/icons/16/editor/Code16.svelte';
import I6 from '$lib/icons/16/editor/CodeBinary16.svelte';
import I7 from '$lib/icons/16/editor/ColorPantone16.svelte';
import I8 from '$lib/icons/16/editor/ColumnDelete16.svelte';
import I9 from '$lib/icons/16/editor/ColumnLeft16.svelte';
import I10 from '$lib/icons/16/editor/ColumnRight16.svelte';
import I11 from '$lib/icons/16/editor/CompareAdd16.svelte';
import I12 from '$lib/icons/16/editor/CompareAdded16.svelte';
import I13 from '$lib/icons/16/editor/Crop16.svelte';
import I14 from '$lib/icons/16/editor/DividerDot16.svelte';
import I15 from '$lib/icons/16/editor/DividerHorizontal16.svelte';
import I16 from '$lib/icons/16/editor/DividerVertical16.svelte';
import I17 from '$lib/icons/16/editor/DragHorizontalDots16.svelte';
import I18 from '$lib/icons/16/editor/DragHorizontalLines16.svelte';
import I19 from '$lib/icons/16/editor/DragVerticalDots16.svelte';
import I20 from '$lib/icons/16/editor/DragVerticalLines16.svelte';
import I21 from '$lib/icons/16/editor/Edit16.svelte';
import I22 from '$lib/icons/16/editor/En16.svelte';
import I23 from '$lib/icons/16/editor/EndOfLine16.svelte';
import I24 from '$lib/icons/16/editor/Equals16.svelte';
import I25 from '$lib/icons/16/editor/Eraser16.svelte';
import I26 from '$lib/icons/16/editor/Eyedropper16.svelte';
import I27 from '$lib/icons/16/editor/EyedropperFill16.svelte';
import I28 from '$lib/icons/16/editor/GridColumns116.svelte';
import I29 from '$lib/icons/16/editor/GridColumns216.svelte';
import I30 from '$lib/icons/16/editor/GridColumns316.svelte';
import I31 from '$lib/icons/16/editor/GridGant16.svelte';
import I32 from '$lib/icons/16/editor/GridPanelLeft16.svelte';
import I33 from '$lib/icons/16/editor/GridPanelRight16.svelte';
import I34 from '$lib/icons/16/editor/GridTablet16.svelte';
import I35 from '$lib/icons/16/editor/Hashtag16.svelte';
import I36 from '$lib/icons/16/editor/Inputs16.svelte';
import I37 from '$lib/icons/16/editor/LetterSpacing16.svelte';
import I38 from '$lib/icons/16/editor/LineSpacing16.svelte';
import I39 from '$lib/icons/16/editor/ListBulleted16.svelte';
import I40 from '$lib/icons/16/editor/ListChecked16.svelte';
import I41 from '$lib/icons/16/editor/ListNumbered16.svelte';
import I42 from '$lib/icons/16/editor/ListUnchecked16.svelte';
import I43 from '$lib/icons/16/editor/Marker16.svelte';
import I44 from '$lib/icons/16/editor/MarketingFunnel16.svelte';
import I45 from '$lib/icons/16/editor/MiddleOfLine16.svelte';
import I46 from '$lib/icons/16/editor/Monospace16.svelte';
import I47 from '$lib/icons/16/editor/NullAdd16.svelte';
import I48 from '$lib/icons/16/editor/NullDelete16.svelte';
import I49 from '$lib/icons/16/editor/Numbers16.svelte';
import I50 from '$lib/icons/16/editor/ObjectAlignBottomVertical16.svelte';
import I51 from '$lib/icons/16/editor/ObjectAlignCenterHorizontal16.svelte';
import I52 from '$lib/icons/16/editor/ObjectAlignCenterVertical16.svelte';
import I53 from '$lib/icons/16/editor/ObjectAlignDistanceHorizontal16.svelte';
import I54 from '$lib/icons/16/editor/ObjectAlignDistanceVertical16.svelte';
import I55 from '$lib/icons/16/editor/ObjectAlignDividerHorizontal16.svelte';
import I56 from '$lib/icons/16/editor/ObjectAlignDividerVertical16.svelte';
import I57 from '$lib/icons/16/editor/ObjectAlignLeftHorizontal16.svelte';
import I58 from '$lib/icons/16/editor/ObjectAlignRightHorizontal16.svelte';
import I59 from '$lib/icons/16/editor/ObjectAlignTopVertical16.svelte';
import I60 from '$lib/icons/16/editor/Objects16.svelte';
import I61 from '$lib/icons/16/editor/PaintBucket16.svelte';
import I62 from '$lib/icons/16/editor/PaintBucketFill16.svelte';
import I63 from '$lib/icons/16/editor/Pen16.svelte';
import I64 from '$lib/icons/16/editor/PenTool16.svelte';
import I65 from '$lib/icons/16/editor/Pencil16.svelte';
import I66 from '$lib/icons/16/editor/Plumage16.svelte';
import I67 from '$lib/icons/16/editor/Quote16.svelte';
import I68 from '$lib/icons/16/editor/Radiobutton16.svelte';
import I69 from '$lib/icons/16/editor/Rename16.svelte';
import I70 from '$lib/icons/16/editor/Rotate3D16.svelte';
import I71 from '$lib/icons/16/editor/RowAbove16.svelte';
import I72 from '$lib/icons/16/editor/RowBelow16.svelte';
import I73 from '$lib/icons/16/editor/RowDelete16.svelte';
import I74 from '$lib/icons/16/editor/Ru16.svelte';
import I75 from '$lib/icons/16/editor/Scissors16.svelte';
import I76 from '$lib/icons/16/editor/Separator16.svelte';
import I77 from '$lib/icons/16/editor/Sigma16.svelte';
import I78 from '$lib/icons/16/editor/SortDown16.svelte';
import I79 from '$lib/icons/16/editor/SortUp16.svelte';
import I80 from '$lib/icons/16/editor/StartOfLine16.svelte';
import I81 from '$lib/icons/16/editor/Terminal16.svelte';
import I82 from '$lib/icons/16/editor/Text16.svelte';
import I83 from '$lib/icons/16/editor/TextAlignCenter16.svelte';
import I84 from '$lib/icons/16/editor/TextAlignDistance16.svelte';
import I85 from '$lib/icons/16/editor/TextAlignLeft16.svelte';
import I86 from '$lib/icons/16/editor/TextAlignRight16.svelte';
import I87 from '$lib/icons/16/editor/TextBold16.svelte';
import I88 from '$lib/icons/16/editor/TextCapsLock16.svelte';
import I89 from '$lib/icons/16/editor/TextItalic16.svelte';
import I90 from '$lib/icons/16/editor/TextLower16.svelte';
import I91 from '$lib/icons/16/editor/TextRise16.svelte';
import I92 from '$lib/icons/16/editor/TextSearch16.svelte';
import I93 from '$lib/icons/16/editor/TextStrikethrough16.svelte';
import I94 from '$lib/icons/16/editor/TextSubscript16.svelte';
import I95 from '$lib/icons/16/editor/TextSuperscript16.svelte';
import I96 from '$lib/icons/16/editor/TextUnderline16.svelte';
import I97 from '$lib/icons/16/editor/Translate16.svelte';
import I98 from '$lib/icons/16/editor/Value16.svelte';

export default {
	"Array16": I0,
	"Bullet16": I1,
	"CellsMerge16": I2,
	"Checkbox16": I3,
	"CheckboxGroup16": I4,
	"Code16": I5,
	"CodeBinary16": I6,
	"ColorPantone16": I7,
	"ColumnDelete16": I8,
	"ColumnLeft16": I9,
	"ColumnRight16": I10,
	"CompareAdd16": I11,
	"CompareAdded16": I12,
	"Crop16": I13,
	"DividerDot16": I14,
	"DividerHorizontal16": I15,
	"DividerVertical16": I16,
	"DragHorizontalDots16": I17,
	"DragHorizontalLines16": I18,
	"DragVerticalDots16": I19,
	"DragVerticalLines16": I20,
	"Edit16": I21,
	"En16": I22,
	"EndOfLine16": I23,
	"Equals16": I24,
	"Eraser16": I25,
	"Eyedropper16": I26,
	"EyedropperFill16": I27,
	"GridColumns116": I28,
	"GridColumns216": I29,
	"GridColumns316": I30,
	"GridGant16": I31,
	"GridPanelLeft16": I32,
	"GridPanelRight16": I33,
	"GridTablet16": I34,
	"Hashtag16": I35,
	"Inputs16": I36,
	"LetterSpacing16": I37,
	"LineSpacing16": I38,
	"ListBulleted16": I39,
	"ListChecked16": I40,
	"ListNumbered16": I41,
	"ListUnchecked16": I42,
	"Marker16": I43,
	"MarketingFunnel16": I44,
	"MiddleOfLine16": I45,
	"Monospace16": I46,
	"NullAdd16": I47,
	"NullDelete16": I48,
	"Numbers16": I49,
	"ObjectAlignBottomVertical16": I50,
	"ObjectAlignCenterHorizontal16": I51,
	"ObjectAlignCenterVertical16": I52,
	"ObjectAlignDistanceHorizontal16": I53,
	"ObjectAlignDistanceVertical16": I54,
	"ObjectAlignDividerHorizontal16": I55,
	"ObjectAlignDividerVertical16": I56,
	"ObjectAlignLeftHorizontal16": I57,
	"ObjectAlignRightHorizontal16": I58,
	"ObjectAlignTopVertical16": I59,
	"Objects16": I60,
	"PaintBucket16": I61,
	"PaintBucketFill16": I62,
	"Pen16": I63,
	"PenTool16": I64,
	"Pencil16": I65,
	"Plumage16": I66,
	"Quote16": I67,
	"Radiobutton16": I68,
	"Rename16": I69,
	"Rotate3D16": I70,
	"RowAbove16": I71,
	"RowBelow16": I72,
	"RowDelete16": I73,
	"Ru16": I74,
	"Scissors16": I75,
	"Separator16": I76,
	"Sigma16": I77,
	"SortDown16": I78,
	"SortUp16": I79,
	"StartOfLine16": I80,
	"Terminal16": I81,
	"Text16": I82,
	"TextAlignCenter16": I83,
	"TextAlignDistance16": I84,
	"TextAlignLeft16": I85,
	"TextAlignRight16": I86,
	"TextBold16": I87,
	"TextCapsLock16": I88,
	"TextItalic16": I89,
	"TextLower16": I90,
	"TextRise16": I91,
	"TextSearch16": I92,
	"TextStrikethrough16": I93,
	"TextSubscript16": I94,
	"TextSuperscript16": I95,
	"TextUnderline16": I96,
	"Translate16": I97,
	"Value16": I98
};
