// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/logo/index.js (order kept)
import I0 from '$lib/icons/16/logo/AndroidFill16.svelte';
import I1 from '$lib/icons/16/logo/AppleFill16.svelte';
import I2 from '$lib/icons/16/logo/DrWeb16.svelte';
import I3 from '$lib/icons/16/logo/EsetNod16.svelte';
import I4 from '$lib/icons/16/logo/FlickrFill16.svelte';
import I5 from '$lib/icons/16/logo/GithubFill16.svelte';
import I6 from '$lib/icons/16/logo/GitlabFill16.svelte';
import I7 from '$lib/icons/16/logo/GooglePlayFill16.svelte';
import I8 from '$lib/icons/16/logo/Googleplus16.svelte';
import I9 from '$lib/icons/16/logo/Gosuslugi16.svelte';
import I10 from '$lib/icons/16/logo/Kluch16.svelte';
import I11 from '$lib/icons/16/logo/KluchFill16.svelte';
import I12 from '$lib/icons/16/logo/Licey16.svelte';
import I13 from '$lib/icons/16/logo/LiceyFill16.svelte';
import I14 from '$lib/icons/16/logo/Mailru16.svelte';
import I15 from '$lib/icons/16/logo/Max16.svelte';
import I16 from '$lib/icons/16/logo/MicrosoftOffice16.svelte';
import I17 from '$lib/icons/16/logo/OdnoklassnikiFill16.svelte';
import I18 from '$lib/icons/16/logo/Onlime16.svelte';
import I19 from '$lib/icons/16/logo/OnlimeFill16.svelte';
import I20 from '$lib/icons/16/logo/Rostelecom16.svelte';
import I21 from '$lib/icons/16/logo/RostelecomFill16.svelte';
import I22 from '$lib/icons/16/logo/RostelecomSmartHome16.svelte';
import I23 from '$lib/icons/16/logo/RostelecomSmartHomeFill16.svelte';
import I24 from '$lib/icons/16/logo/Sber16.svelte';
import I25 from '$lib/icons/16/logo/TamTam16.svelte';
import I26 from '$lib/icons/16/logo/TelegramFill16.svelte';
import I27 from '$lib/icons/16/logo/TwitterFill16.svelte';
import I28 from '$lib/icons/16/logo/Viber16.svelte';
import I29 from '$lib/icons/16/logo/VkontakteFill16.svelte';
import I30 from '$lib/icons/16/logo/WhatsApp16.svelte';
import I31 from '$lib/icons/16/logo/WindowsFill16.svelte';
import I32 from '$lib/icons/16/logo/Wink16.svelte';
import I33 from '$lib/icons/16/logo/WinkFill16.svelte';
import I34 from '$lib/icons/16/logo/Yandex16.svelte';
import I35 from '$lib/icons/16/logo/YandexDisk16.svelte';
import I36 from '$lib/icons/16/logo/YoutubeFill16.svelte';

export default {
	"AndroidFill16": I0,
	"AppleFill16": I1,
	"DrWeb16": I2,
	"EsetNod16": I3,
	"FlickrFill16": I4,
	"GithubFill16": I5,
	"GitlabFill16": I6,
	"GooglePlayFill16": I7,
	"Googleplus16": I8,
	"Gosuslugi16": I9,
	"Kluch16": I10,
	"KluchFill16": I11,
	"Licey16": I12,
	"LiceyFill16": I13,
	"Mailru16": I14,
	"Max16": I15,
	"MicrosoftOffice16": I16,
	"OdnoklassnikiFill16": I17,
	"Onlime16": I18,
	"OnlimeFill16": I19,
	"Rostelecom16": I20,
	"RostelecomFill16": I21,
	"RostelecomSmartHome16": I22,
	"RostelecomSmartHomeFill16": I23,
	"Sber16": I24,
	"TamTam16": I25,
	"TelegramFill16": I26,
	"TwitterFill16": I27,
	"Viber16": I28,
	"VkontakteFill16": I29,
	"WhatsApp16": I30,
	"WindowsFill16": I31,
	"Wink16": I32,
	"WinkFill16": I33,
	"Yandex16": I34,
	"YandexDisk16": I35,
	"YoutubeFill16": I36
};
