// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/media/index.js (order kept)
import I0 from '$lib/icons/16/media/Camera16.svelte';
import I1 from '$lib/icons/16/media/CameraFill16.svelte';
import I2 from '$lib/icons/16/media/CameraOff16.svelte';
import I3 from '$lib/icons/16/media/CameraOffFill16.svelte';
import I4 from '$lib/icons/16/media/FastForward16.svelte';
import I5 from '$lib/icons/16/media/FastRewind3316.svelte';
import I6 from '$lib/icons/16/media/GalleryHorizontal16.svelte';
import I7 from '$lib/icons/16/media/GalleryVertical16.svelte';
import I8 from '$lib/icons/16/media/Headphones16.svelte';
import I9 from '$lib/icons/16/media/Image16.svelte';
import I10 from '$lib/icons/16/media/Maximize16.svelte';
import I11 from '$lib/icons/16/media/Megaphone16.svelte';
import I12 from '$lib/icons/16/media/Melody16.svelte';
import I13 from '$lib/icons/16/media/MelodyTone16.svelte';
import I14 from '$lib/icons/16/media/Microphone16.svelte';
import I15 from '$lib/icons/16/media/MicrophoneFill16.svelte';
import I16 from '$lib/icons/16/media/MicrophoneMute16.svelte';
import I17 from '$lib/icons/16/media/MicrophoneMuteFill16.svelte';
import I18 from '$lib/icons/16/media/MicrophoneTalker16.svelte';
import I19 from '$lib/icons/16/media/Minimize16.svelte';
import I20 from '$lib/icons/16/media/Pause16.svelte';
import I21 from '$lib/icons/16/media/PauseFill16.svelte';
import I22 from '$lib/icons/16/media/Photo16.svelte';
import I23 from '$lib/icons/16/media/Play16.svelte';
import I24 from '$lib/icons/16/media/PlayFill16.svelte';
import I25 from '$lib/icons/16/media/PlayNext16.svelte';
import I26 from '$lib/icons/16/media/PlayPrevious16.svelte';
import I27 from '$lib/icons/16/media/ScreenControl16.svelte';
import I28 from '$lib/icons/16/media/SpeedPlayback16.svelte';
import I29 from '$lib/icons/16/media/Stop16.svelte';
import I30 from '$lib/icons/16/media/StopFill16.svelte';
import I31 from '$lib/icons/16/media/Voice16.svelte';
import I32 from '$lib/icons/16/media/VolumeDown16.svelte';
import I33 from '$lib/icons/16/media/VolumeDownFill16.svelte';
import I34 from '$lib/icons/16/media/VolumeOff16.svelte';
import I35 from '$lib/icons/16/media/VolumeOffFill16.svelte';
import I36 from '$lib/icons/16/media/VolumeUp16.svelte';
import I37 from '$lib/icons/16/media/VolumeUpFill16.svelte';

export default {
	"Camera16": I0,
	"CameraFill16": I1,
	"CameraOff16": I2,
	"CameraOffFill16": I3,
	"FastForward16": I4,
	"FastRewind3316": I5,
	"GalleryHorizontal16": I6,
	"GalleryVertical16": I7,
	"Headphones16": I8,
	"Image16": I9,
	"Maximize16": I10,
	"Megaphone16": I11,
	"Melody16": I12,
	"MelodyTone16": I13,
	"Microphone16": I14,
	"MicrophoneFill16": I15,
	"MicrophoneMute16": I16,
	"MicrophoneMuteFill16": I17,
	"MicrophoneTalker16": I18,
	"Minimize16": I19,
	"Pause16": I20,
	"PauseFill16": I21,
	"Photo16": I22,
	"Play16": I23,
	"PlayFill16": I24,
	"PlayNext16": I25,
	"PlayPrevious16": I26,
	"ScreenControl16": I27,
	"SpeedPlayback16": I28,
	"Stop16": I29,
	"StopFill16": I30,
	"Voice16": I31,
	"VolumeDown16": I32,
	"VolumeDownFill16": I33,
	"VolumeOff16": I34,
	"VolumeOffFill16": I35,
	"VolumeUp16": I36,
	"VolumeUpFill16": I37
};
