// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/navigation/index.js (order kept)
import I0 from '$lib/icons/16/navigation/ArrowDown16.svelte';
import I1 from '$lib/icons/16/navigation/ArrowForwardLeft16.svelte';
import I2 from '$lib/icons/16/navigation/ArrowForwardRight16.svelte';
import I3 from '$lib/icons/16/navigation/ArrowLeft16.svelte';
import I4 from '$lib/icons/16/navigation/ArrowLeftDown16.svelte';
import I5 from '$lib/icons/16/navigation/ArrowLeftUp16.svelte';
import I6 from '$lib/icons/16/navigation/ArrowRight16.svelte';
import I7 from '$lib/icons/16/navigation/ArrowRightDown16.svelte';
import I8 from '$lib/icons/16/navigation/ArrowRightLeft16.svelte';
import I9 from '$lib/icons/16/navigation/ArrowRightUp16.svelte';
import I10 from '$lib/icons/16/navigation/ArrowUp16.svelte';
import I11 from '$lib/icons/16/navigation/ArrowUpDown16.svelte';
import I12 from '$lib/icons/16/navigation/CaretSort16.svelte';
import I13 from '$lib/icons/16/navigation/CaretSortDown16.svelte';
import I14 from '$lib/icons/16/navigation/CaretSortUp16.svelte';
import I15 from '$lib/icons/16/navigation/CheckLarge16.svelte';
import I16 from '$lib/icons/16/navigation/CheckLargeDouble16.svelte';
import I17 from '$lib/icons/16/navigation/CheckSmall16.svelte';
import I18 from '$lib/icons/16/navigation/ChevronDown16.svelte';
import I19 from '$lib/icons/16/navigation/ChevronLeft16.svelte';
import I20 from '$lib/icons/16/navigation/ChevronRight16.svelte';
import I21 from '$lib/icons/16/navigation/ChevronSort16.svelte';
import I22 from '$lib/icons/16/navigation/ChevronUp16.svelte';
import I23 from '$lib/icons/16/navigation/CloseLarge16.svelte';
import I24 from '$lib/icons/16/navigation/CloseSmall16.svelte';
import I25 from '$lib/icons/16/navigation/Flag16.svelte';
import I26 from '$lib/icons/16/navigation/FlagMini16.svelte';
import I27 from '$lib/icons/16/navigation/Fold16.svelte';
import I28 from '$lib/icons/16/navigation/Geolocation16.svelte';
import I29 from '$lib/icons/16/navigation/GeolocationFill16.svelte';
import I30 from '$lib/icons/16/navigation/LinkNative16.svelte';
import I31 from '$lib/icons/16/navigation/Map16.svelte';
import I32 from '$lib/icons/16/navigation/Menu16.svelte';
import I33 from '$lib/icons/16/navigation/MenuCatalog16.svelte';
import I34 from '$lib/icons/16/navigation/MenuFuture16.svelte';
import I35 from '$lib/icons/16/navigation/MenuFutureKebab16.svelte';
import I36 from '$lib/icons/16/navigation/MenuFuturePlusBullets16.svelte';
import I37 from '$lib/icons/16/navigation/MenuKebab16.svelte';
import I38 from '$lib/icons/16/navigation/MenuPlusBullets16.svelte';
import I39 from '$lib/icons/16/navigation/More16.svelte';
import I40 from '$lib/icons/16/navigation/Navigation16.svelte';
import I41 from '$lib/icons/16/navigation/Next16.svelte';
import I42 from '$lib/icons/16/navigation/Pin16.svelte';
import I43 from '$lib/icons/16/navigation/PinFill16.svelte';
import I44 from '$lib/icons/16/navigation/Previous16.svelte';
import I45 from '$lib/icons/16/navigation/Redo16.svelte';
import I46 from '$lib/icons/16/navigation/SearchEmpty16.svelte';
import I47 from '$lib/icons/16/navigation/SearchMinus16.svelte';
import I48 from '$lib/icons/16/navigation/SearchPlus16.svelte';
import I49 from '$lib/icons/16/navigation/SignIn16.svelte';
import I50 from '$lib/icons/16/navigation/SignOut16.svelte';
import I51 from '$lib/icons/16/navigation/TreeForwardLeft16.svelte';
import I52 from '$lib/icons/16/navigation/TreeForwardRight16.svelte';
import I53 from '$lib/icons/16/navigation/Undo16.svelte';
import I54 from '$lib/icons/16/navigation/Unfold16.svelte';

export default {
	"ArrowDown16": I0,
	"ArrowForwardLeft16": I1,
	"ArrowForwardRight16": I2,
	"ArrowLeft16": I3,
	"ArrowLeftDown16": I4,
	"ArrowLeftUp16": I5,
	"ArrowRight16": I6,
	"ArrowRightDown16": I7,
	"ArrowRightLeft16": I8,
	"ArrowRightUp16": I9,
	"ArrowUp16": I10,
	"ArrowUpDown16": I11,
	"CaretSort16": I12,
	"CaretSortDown16": I13,
	"CaretSortUp16": I14,
	"CheckLarge16": I15,
	"CheckLargeDouble16": I16,
	"CheckSmall16": I17,
	"ChevronDown16": I18,
	"ChevronLeft16": I19,
	"ChevronRight16": I20,
	"ChevronSort16": I21,
	"ChevronUp16": I22,
	"CloseLarge16": I23,
	"CloseSmall16": I24,
	"Flag16": I25,
	"FlagMini16": I26,
	"Fold16": I27,
	"Geolocation16": I28,
	"GeolocationFill16": I29,
	"LinkNative16": I30,
	"Map16": I31,
	"Menu16": I32,
	"MenuCatalog16": I33,
	"MenuFuture16": I34,
	"MenuFutureKebab16": I35,
	"MenuFuturePlusBullets16": I36,
	"MenuKebab16": I37,
	"MenuPlusBullets16": I38,
	"More16": I39,
	"Navigation16": I40,
	"Next16": I41,
	"Pin16": I42,
	"PinFill16": I43,
	"Previous16": I44,
	"Redo16": I45,
	"SearchEmpty16": I46,
	"SearchMinus16": I47,
	"SearchPlus16": I48,
	"SignIn16": I49,
	"SignOut16": I50,
	"TreeForwardLeft16": I51,
	"TreeForwardRight16": I52,
	"Undo16": I53,
	"Unfold16": I54
};
