// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/place/index.js (order kept)
import I0 from '$lib/icons/16/place/Anchor16.svelte';
import I1 from '$lib/icons/16/place/BackyardTree16.svelte';
import I2 from '$lib/icons/16/place/Cloud16.svelte';
import I3 from '$lib/icons/16/place/CoffeeBreak16.svelte';
import I4 from '$lib/icons/16/place/DarkTheme16.svelte';
import I5 from '$lib/icons/16/place/Fire16.svelte';
import I6 from '$lib/icons/16/place/Kettlebell16.svelte';
import I7 from '$lib/icons/16/place/Launch16.svelte';
import I8 from '$lib/icons/16/place/Plane16.svelte';
import I9 from '$lib/icons/16/place/Tribune16.svelte';

export default {
	"Anchor16": I0,
	"BackyardTree16": I1,
	"Cloud16": I2,
	"CoffeeBreak16": I3,
	"DarkTheme16": I4,
	"Fire16": I5,
	"Kettlebell16": I6,
	"Launch16": I7,
	"Plane16": I8,
	"Tribune16": I9
};
