// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/rating/index.js (order kept)
import I0 from '$lib/icons/16/rating/Dislike16.svelte';
import I1 from '$lib/icons/16/rating/DislikeFill16.svelte';
import I2 from '$lib/icons/16/rating/Favorite16.svelte';
import I3 from '$lib/icons/16/rating/FavoriteFill16.svelte';
import I4 from '$lib/icons/16/rating/Heart16.svelte';
import I5 from '$lib/icons/16/rating/HeartFill16.svelte';
import I6 from '$lib/icons/16/rating/Like16.svelte';
import I7 from '$lib/icons/16/rating/LikeFill16.svelte';
import I8 from '$lib/icons/16/rating/PriorityHigh16.svelte';
import I9 from '$lib/icons/16/rating/PriorityHighFill16.svelte';
import I10 from '$lib/icons/16/rating/PriorityLow16.svelte';
import I11 from '$lib/icons/16/rating/PriorityLowFill16.svelte';
import I12 from '$lib/icons/16/rating/PriorityNegativeLow16.svelte';
import I13 from '$lib/icons/16/rating/PriorityNegativeLowFill16.svelte';
import I14 from '$lib/icons/16/rating/PriorityNegativeNormal16.svelte';
import I15 from '$lib/icons/16/rating/PriorityNegativeNormalFill16.svelte';
import I16 from '$lib/icons/16/rating/PriorityNormal16.svelte';
import I17 from '$lib/icons/16/rating/PriorityNormalFill16.svelte';
import I18 from '$lib/icons/16/rating/PriorityVeryHigh16.svelte';
import I19 from '$lib/icons/16/rating/PriorityVeryHighFill16.svelte';
import I20 from '$lib/icons/16/rating/Rating16.svelte';
import I21 from '$lib/icons/16/rating/RatingFill16.svelte';
import I22 from '$lib/icons/16/rating/RatingHalf16.svelte';
import I23 from '$lib/icons/16/rating/RatingNo16.svelte';

export default {
	"Dislike16": I0,
	"DislikeFill16": I1,
	"Favorite16": I2,
	"FavoriteFill16": I3,
	"Heart16": I4,
	"HeartFill16": I5,
	"Like16": I6,
	"LikeFill16": I7,
	"PriorityHigh16": I8,
	"PriorityHighFill16": I9,
	"PriorityLow16": I10,
	"PriorityLowFill16": I11,
	"PriorityNegativeLow16": I12,
	"PriorityNegativeLowFill16": I13,
	"PriorityNegativeNormal16": I14,
	"PriorityNegativeNormalFill16": I15,
	"PriorityNormal16": I16,
	"PriorityNormalFill16": I17,
	"PriorityVeryHigh16": I18,
	"PriorityVeryHighFill16": I19,
	"Rating16": I20,
	"RatingFill16": I21,
	"RatingHalf16": I22,
	"RatingNo16": I23
};
