// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/16/technology/index.js (order kept)
import I0 from '$lib/icons/16/technology/AllDevices16.svelte';
import I1 from '$lib/icons/16/technology/Blueto16.svelte';
import I2 from '$lib/icons/16/technology/Datastore16.svelte';
import I3 from '$lib/icons/16/technology/Desktop16.svelte';
import I4 from '$lib/icons/16/technology/FloppyDisk16.svelte';
import I5 from '$lib/icons/16/technology/Internet16.svelte';
import I6 from '$lib/icons/16/technology/Mobile16.svelte';
import I7 from '$lib/icons/16/technology/Phone16.svelte';
import I8 from '$lib/icons/16/technology/Tablet16.svelte';
import I9 from '$lib/icons/16/technology/Wifi16.svelte';
import I10 from '$lib/icons/16/technology/WifiDisconnect16.svelte';
import I11 from '$lib/icons/16/technology/WifiOff16.svelte';

export default {
	"AllDevices16": I0,
	"Blueto16": I1,
	"Datastore16": I2,
	"Desktop16": I3,
	"FloppyDisk16": I4,
	"Internet16": I5,
	"Mobile16": I6,
	"Phone16": I7,
	"Tablet16": I8,
	"Wifi16": I9,
	"WifiDisconnect16": I10,
	"WifiOff16": I11
};
