// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/action/index.js (order kept)
import I0 from '$lib/icons/24/action/AddLarge.svelte';
import I1 from '$lib/icons/24/action/AddSmall.svelte';
import I2 from '$lib/icons/24/action/Arrow.svelte';
import I3 from '$lib/icons/24/action/Attachment.svelte';
import I4 from '$lib/icons/24/action/AttachmentLink.svelte';
import I5 from '$lib/icons/24/action/AttachmentLinkAdd.svelte';
import I6 from '$lib/icons/24/action/AttachmentLinkBreak.svelte';
import I7 from '$lib/icons/24/action/Attention.svelte';
import I8 from '$lib/icons/24/action/AttentionMark.svelte';
import I9 from '$lib/icons/24/action/Backspace.svelte';
import I10 from '$lib/icons/24/action/BackspaceFill.svelte';
import I11 from '$lib/icons/24/action/BarCode.svelte';
import I12 from '$lib/icons/24/action/BarID.svelte';
import I13 from '$lib/icons/24/action/BlockAdd.svelte';
import I14 from '$lib/icons/24/action/Catalog.svelte';
import I15 from '$lib/icons/24/action/CatalogAdd.svelte';
import I16 from '$lib/icons/24/action/CheckEdit.svelte';
import I17 from '$lib/icons/24/action/CheckStatistics.svelte';
import I18 from '$lib/icons/24/action/Checklist.svelte';
import I19 from '$lib/icons/24/action/CloudDownload.svelte';
import I20 from '$lib/icons/24/action/CloudUpload.svelte';
import I21 from '$lib/icons/24/action/Copy.svelte';
import I22 from '$lib/icons/24/action/Download.svelte';
import I23 from '$lib/icons/24/action/Empty.svelte';
import I24 from '$lib/icons/24/action/Equaliser.svelte';
import I25 from '$lib/icons/24/action/EqualiserClear.svelte';
import I26 from '$lib/icons/24/action/FaceID.svelte';
import I27 from '$lib/icons/24/action/Filter.svelte';
import I28 from '$lib/icons/24/action/FilterAdd.svelte';
import I29 from '$lib/icons/24/action/FilterClear.svelte';
import I30 from '$lib/icons/24/action/FilterFill.svelte';
import I31 from '$lib/icons/24/action/GalleryCards.svelte';
import I32 from '$lib/icons/24/action/HeartList.svelte';
import I33 from '$lib/icons/24/action/Home.svelte';
import I34 from '$lib/icons/24/action/ImageRotation.svelte';
import I35 from '$lib/icons/24/action/KeyOld.svelte';
import I36 from '$lib/icons/24/action/KeyPassword.svelte';
import I37 from '$lib/icons/24/action/Link.svelte';
import I38 from '$lib/icons/24/action/Lock.svelte';
import I39 from '$lib/icons/24/action/LockAdd.svelte';
import I40 from '$lib/icons/24/action/Mouse.svelte';
import I41 from '$lib/icons/24/action/Notification.svelte';
import I42 from '$lib/icons/24/action/NotificationNew.svelte';
import I43 from '$lib/icons/24/action/NotificationOff.svelte';
import I44 from '$lib/icons/24/action/PIN.svelte';
import I45 from '$lib/icons/24/action/Password.svelte';
import I46 from '$lib/icons/24/action/PasswordHide.svelte';
import I47 from '$lib/icons/24/action/PasswordShow.svelte';
import I48 from '$lib/icons/24/action/Pointer.svelte';
import I49 from '$lib/icons/24/action/Print.svelte';
import I50 from '$lib/icons/24/action/ProgressDownload.svelte';
import I51 from '$lib/icons/24/action/PushPin.svelte';
import I52 from '$lib/icons/24/action/PushPinFill.svelte';
import I53 from '$lib/icons/24/action/PushPinOff.svelte';
import I54 from '$lib/icons/24/action/PushPinOffFill.svelte';
import I55 from '$lib/icons/24/action/QRCode.svelte';
import I56 from '$lib/icons/24/action/QRID.svelte';
import I57 from '$lib/icons/24/action/Reboot.svelte';
import I58 from '$lib/icons/24/action/Refresh.svelte';
import I59 from '$lib/icons/24/action/RefreshSmall.svelte';
import I60 from '$lib/icons/24/action/Release.svelte';
import I61 from '$lib/icons/24/action/RemoveLarge.svelte';
import I62 from '$lib/icons/24/action/RemoveSmall.svelte';
import I63 from '$lib/icons/24/action/SOS.svelte';
import I64 from '$lib/icons/24/action/Search.svelte';
import I65 from '$lib/icons/24/action/Security.svelte';
import I66 from '$lib/icons/24/action/SecurityCheck.svelte';
import I67 from '$lib/icons/24/action/SecurityHealth.svelte';
import I68 from '$lib/icons/24/action/SecurityRules.svelte';
import I69 from '$lib/icons/24/action/Send.svelte';
import I70 from '$lib/icons/24/action/Settings.svelte';
import I71 from '$lib/icons/24/action/SettingsAdjust.svelte';
import I72 from '$lib/icons/24/action/SwitchOff.svelte';
import I73 from '$lib/icons/24/action/SwitchOn.svelte';
import I74 from '$lib/icons/24/action/Synchronization.svelte';
import I75 from '$lib/icons/24/action/SynchronizationSmall.svelte';
import I76 from '$lib/icons/24/action/TouchID.svelte';
import I77 from '$lib/icons/24/action/Trash.svelte';
import I78 from '$lib/icons/24/action/Unlock.svelte';
import I79 from '$lib/icons/24/action/Upload.svelte';

export default {
	"AddLarge": I0,
	"AddSmall": I1,
	"Arrow": I2,
	"Attachment": I3,
	"AttachmentLink": I4,
	"AttachmentLinkAdd": I5,
	"AttachmentLinkBreak": I6,
	"Attention": I7,
	"AttentionMark": I8,
	"Backspace": I9,
	"BackspaceFill": I10,
	"BarCode": I11,
	"BarID": I12,
	"BlockAdd": I13,
	"Catalog": I14,
	"CatalogAdd": I15,
	"CheckEdit": I16,
	"CheckStatistics": I17,
	"Checklist": I18,
	"CloudDownload": I19,
	"CloudUpload": I20,
	"Copy": I21,
	"Download": I22,
	"Empty": I23,
	"Equaliser": I24,
	"EqualiserClear": I25,
	"FaceID": I26,
	"Filter": I27,
	"FilterAdd": I28,
	"FilterClear": I29,
	"FilterFill": I30,
	"GalleryCards": I31,
	"HeartList": I32,
	"Home": I33,
	"ImageRotation": I34,
	"KeyOld": I35,
	"KeyPassword": I36,
	"Link": I37,
	"Lock": I38,
	"LockAdd": I39,
	"Mouse": I40,
	"Notification": I41,
	"NotificationNew": I42,
	"NotificationOff": I43,
	"PIN": I44,
	"Password": I45,
	"PasswordHide": I46,
	"PasswordShow": I47,
	"Pointer": I48,
	"Print": I49,
	"ProgressDownload": I50,
	"PushPin": I51,
	"PushPinFill": I52,
	"PushPinOff": I53,
	"PushPinOffFill": I54,
	"QRCode": I55,
	"QRID": I56,
	"Reboot": I57,
	"Refresh": I58,
	"RefreshSmall": I59,
	"Release": I60,
	"RemoveLarge": I61,
	"RemoveSmall": I62,
	"SOS": I63,
	"Search": I64,
	"Security": I65,
	"SecurityCheck": I66,
	"SecurityHealth": I67,
	"SecurityRules": I68,
	"Send": I69,
	"Settings": I70,
	"SettingsAdjust": I71,
	"SwitchOff": I72,
	"SwitchOn": I73,
	"Synchronization": I74,
	"SynchronizationSmall": I75,
	"TouchID": I76,
	"Trash": I77,
	"Unlock": I78,
	"Upload": I79
};
