// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/alert/index.js (order kept)
import I0 from '$lib/icons/24/alert/AttentionColor.svelte';
import I1 from '$lib/icons/24/alert/AttentionMonochrome.svelte';
import I2 from '$lib/icons/24/alert/AttentionStroke.svelte';
import I3 from '$lib/icons/24/alert/ErrorColor.svelte';
import I4 from '$lib/icons/24/alert/ErrorMonochrome.svelte';
import I5 from '$lib/icons/24/alert/ErrorStroke.svelte';
import I6 from '$lib/icons/24/alert/HelpColor.svelte';
import I7 from '$lib/icons/24/alert/HelpMonochrome.svelte';
import I8 from '$lib/icons/24/alert/HelpStroke.svelte';
import I9 from '$lib/icons/24/alert/InformationColor.svelte';
import I10 from '$lib/icons/24/alert/InformationMonochrome.svelte';
import I11 from '$lib/icons/24/alert/InformationStroke.svelte';
import I12 from '$lib/icons/24/alert/NoneColor.svelte';
import I13 from '$lib/icons/24/alert/NoneMonochrome.svelte';
import I14 from '$lib/icons/24/alert/NoneStroke.svelte';
import I15 from '$lib/icons/24/alert/OkColor.svelte';
import I16 from '$lib/icons/24/alert/OkMonochrome.svelte';
import I17 from '$lib/icons/24/alert/OkStroke.svelte';
import I18 from '$lib/icons/24/alert/SkipColor.svelte';
import I19 from '$lib/icons/24/alert/SkipMonochrome.svelte';
import I20 from '$lib/icons/24/alert/SkipStroke.svelte';
import I21 from '$lib/icons/24/alert/StopColor.svelte';
import I22 from '$lib/icons/24/alert/StopMonochrome.svelte';
import I23 from '$lib/icons/24/alert/StopStroke.svelte';
import I24 from '$lib/icons/24/alert/TimeColor.svelte';
import I25 from '$lib/icons/24/alert/TimeMonochrome.svelte';
import I26 from '$lib/icons/24/alert/TimeStroke.svelte';

export default {
	"AttentionColor": I0,
	"AttentionMonochrome": I1,
	"AttentionStroke": I2,
	"ErrorColor": I3,
	"ErrorMonochrome": I4,
	"ErrorStroke": I5,
	"HelpColor": I6,
	"HelpMonochrome": I7,
	"HelpStroke": I8,
	"InformationColor": I9,
	"InformationMonochrome": I10,
	"InformationStroke": I11,
	"NoneColor": I12,
	"NoneMonochrome": I13,
	"NoneStroke": I14,
	"OkColor": I15,
	"OkMonochrome": I16,
	"OkStroke": I17,
	"SkipColor": I18,
	"SkipMonochrome": I19,
	"SkipStroke": I20,
	"StopColor": I21,
	"StopMonochrome": I22,
	"StopStroke": I23,
	"TimeColor": I24,
	"TimeMonochrome": I25,
	"TimeStroke": I26
};
