// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/business/index.js (order kept)
import I0 from '$lib/icons/24/business/AreasDiagram.svelte';
import I1 from '$lib/icons/24/business/BarChart.svelte';
import I2 from '$lib/icons/24/business/BoardPresentation.svelte';
import I3 from '$lib/icons/24/business/BoardStatistics.svelte';
import I4 from '$lib/icons/24/business/BoardText.svelte';
import I5 from '$lib/icons/24/business/Calculator.svelte';
import I6 from '$lib/icons/24/business/Cart.svelte';
import I7 from '$lib/icons/24/business/CartOn.svelte';
import I8 from '$lib/icons/24/business/Coupon.svelte';
import I9 from '$lib/icons/24/business/CoworkingSitting.svelte';
import I10 from '$lib/icons/24/business/DeliveryBox.svelte';
import I11 from '$lib/icons/24/business/DeliveryBoxOpened.svelte';
import I12 from '$lib/icons/24/business/DeliveryCourier.svelte';
import I13 from '$lib/icons/24/business/DeliveryEnvelope.svelte';
import I14 from '$lib/icons/24/business/Diamond.svelte';
import I15 from '$lib/icons/24/business/Dollar.svelte';
import I16 from '$lib/icons/24/business/Euro.svelte';
import I17 from '$lib/icons/24/business/Group.svelte';
import I18 from '$lib/icons/24/business/HandCoins.svelte';
import I19 from '$lib/icons/24/business/HandHeart.svelte';
import I20 from '$lib/icons/24/business/Invoice.svelte';
import I21 from '$lib/icons/24/business/Merge.svelte';
import I22 from '$lib/icons/24/business/Motion.svelte';
import I23 from '$lib/icons/24/business/PaymentCard.svelte';
import I24 from '$lib/icons/24/business/PaymentCardPercent.svelte';
import I25 from '$lib/icons/24/business/PaymentCardRuble.svelte';
import I26 from '$lib/icons/24/business/PaymentCardToCard.svelte';
import I27 from '$lib/icons/24/business/Percentage.svelte';
import I28 from '$lib/icons/24/business/PieChart.svelte';
import I29 from '$lib/icons/24/business/Portfolio.svelte';
import I30 from '$lib/icons/24/business/Postcard.svelte';
import I31 from '$lib/icons/24/business/Present.svelte';
import I32 from '$lib/icons/24/business/Promocode.svelte';
import I33 from '$lib/icons/24/business/Reuse.svelte';
import I34 from '$lib/icons/24/business/Ruble.svelte';
import I35 from '$lib/icons/24/business/ScatteringDiagram.svelte';
import I36 from '$lib/icons/24/business/ShoppingBasket.svelte';
import I37 from '$lib/icons/24/business/Shuffle.svelte';
import I38 from '$lib/icons/24/business/Split.svelte';
import I39 from '$lib/icons/24/business/StatisticsCircular.svelte';
import I40 from '$lib/icons/24/business/StatisticsCircularOld.svelte';
import I41 from '$lib/icons/24/business/StatisticsColumn.svelte';
import I42 from '$lib/icons/24/business/StatisticsCurve.svelte';
import I43 from '$lib/icons/24/business/StatisticsLine.svelte';
import I44 from '$lib/icons/24/business/Stickers.svelte';
import I45 from '$lib/icons/24/business/Tie.svelte';
import I46 from '$lib/icons/24/business/Union.svelte';
import I47 from '$lib/icons/24/business/VIP.svelte';
import I48 from '$lib/icons/24/business/Wallet.svelte';
import I49 from '$lib/icons/24/business/WalletOld.svelte';
import I50 from '$lib/icons/24/business/ZeroRuble.svelte';

export default {
	"AreasDiagram": I0,
	"BarChart": I1,
	"BoardPresentation": I2,
	"BoardStatistics": I3,
	"BoardText": I4,
	"Calculator": I5,
	"Cart": I6,
	"CartOn": I7,
	"Coupon": I8,
	"CoworkingSitting": I9,
	"DeliveryBox": I10,
	"DeliveryBoxOpened": I11,
	"DeliveryCourier": I12,
	"DeliveryEnvelope": I13,
	"Diamond": I14,
	"Dollar": I15,
	"Euro": I16,
	"Group": I17,
	"HandCoins": I18,
	"HandHeart": I19,
	"Invoice": I20,
	"Merge": I21,
	"Motion": I22,
	"PaymentCard": I23,
	"PaymentCardPercent": I24,
	"PaymentCardRuble": I25,
	"PaymentCardToCard": I26,
	"Percentage": I27,
	"PieChart": I28,
	"Portfolio": I29,
	"Postcard": I30,
	"Present": I31,
	"Promocode": I32,
	"Reuse": I33,
	"Ruble": I34,
	"ScatteringDiagram": I35,
	"ShoppingBasket": I36,
	"Shuffle": I37,
	"Split": I38,
	"StatisticsCircular": I39,
	"StatisticsCircularOld": I40,
	"StatisticsColumn": I41,
	"StatisticsCurve": I42,
	"StatisticsLine": I43,
	"Stickers": I44,
	"Tie": I45,
	"Union": I46,
	"VIP": I47,
	"Wallet": I48,
	"WalletOld": I49,
	"ZeroRuble": I50
};
