// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/culture/index.js (order kept)
import I0 from '$lib/icons/24/culture/Achievement.svelte';
import I1 from '$lib/icons/24/culture/AdhesivePlaster.svelte';
import I2 from '$lib/icons/24/culture/Backpack.svelte';
import I3 from '$lib/icons/24/culture/Book.svelte';
import I4 from '$lib/icons/24/culture/BookOpen.svelte';
import I5 from '$lib/icons/24/culture/Column.svelte';
import I6 from '$lib/icons/24/culture/Cross.svelte';
import I7 from '$lib/icons/24/culture/Cup.svelte';
import I8 from '$lib/icons/24/culture/Education.svelte';
import I9 from '$lib/icons/24/culture/Emblem.svelte';
import I10 from '$lib/icons/24/culture/FirstAidKit.svelte';
import I11 from '$lib/icons/24/culture/Flask.svelte';
import I12 from '$lib/icons/24/culture/Glasses.svelte';
import I13 from '$lib/icons/24/culture/Globe.svelte';
import I14 from '$lib/icons/24/culture/Government.svelte';
import I15 from '$lib/icons/24/culture/GovernmentFill.svelte';
import I16 from '$lib/icons/24/culture/Insurance.svelte';
import I17 from '$lib/icons/24/culture/Libra.svelte';
import I18 from '$lib/icons/24/culture/Medal.svelte';
import I19 from '$lib/icons/24/culture/Newspaper.svelte';
import I20 from '$lib/icons/24/culture/Palette.svelte';
import I21 from '$lib/icons/24/culture/Passport.svelte';
import I22 from '$lib/icons/24/culture/Phonendoscope.svelte';
import I23 from '$lib/icons/24/culture/Pill.svelte';
import I24 from '$lib/icons/24/culture/PingPong.svelte';
import I25 from '$lib/icons/24/culture/Pulse.svelte';
import I26 from '$lib/icons/24/culture/Seal.svelte';
import I27 from '$lib/icons/24/culture/Syringe.svelte';
import I28 from '$lib/icons/24/culture/TheatreMasks.svelte';
import I29 from '$lib/icons/24/culture/TheatreMasksFill.svelte';
import I30 from '$lib/icons/24/culture/Virus.svelte';

export default {
	"Achievement": I0,
	"AdhesivePlaster": I1,
	"Backpack": I2,
	"Book": I3,
	"BookOpen": I4,
	"Column": I5,
	"Cross": I6,
	"Cup": I7,
	"Education": I8,
	"Emblem": I9,
	"FirstAidKit": I10,
	"Flask": I11,
	"Glasses": I12,
	"Globe": I13,
	"Government": I14,
	"GovernmentFill": I15,
	"Insurance": I16,
	"Libra": I17,
	"Medal": I18,
	"Newspaper": I19,
	"Palette": I20,
	"Passport": I21,
	"Phonendoscope": I22,
	"Pill": I23,
	"PingPong": I24,
	"Pulse": I25,
	"Seal": I26,
	"Syringe": I27,
	"TheatreMasks": I28,
	"TheatreMasksFill": I29,
	"Virus": I30
};
