// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/communication/index.js (order kept)
import I0 from '$lib/icons/24/communication/Aim.svelte';
import I1 from '$lib/icons/24/communication/Alarm.svelte';
import I2 from '$lib/icons/24/communication/Alien.svelte';
import I3 from '$lib/icons/24/communication/At.svelte';
import I4 from '$lib/icons/24/communication/Calendar.svelte';
import I5 from '$lib/icons/24/communication/CalendarAdd.svelte';
import I6 from '$lib/icons/24/communication/CalendarDelete.svelte';
import I7 from '$lib/icons/24/communication/CalendarNumber.svelte';
import I8 from '$lib/icons/24/communication/CalendarOpen.svelte';
import I9 from '$lib/icons/24/communication/CalendarPeriod.svelte';
import I10 from '$lib/icons/24/communication/Call.svelte';
import I11 from '$lib/icons/24/communication/CallDialog.svelte';
import I12 from '$lib/icons/24/communication/CallEnd.svelte';
import I13 from '$lib/icons/24/communication/CallIncoming.svelte';
import I14 from '$lib/icons/24/communication/CallNocoming.svelte';
import I15 from '$lib/icons/24/communication/CallOutgoing.svelte';
import I16 from '$lib/icons/24/communication/Chat.svelte';
import I17 from '$lib/icons/24/communication/ChatNew.svelte';
import I18 from '$lib/icons/24/communication/Comments.svelte';
import I19 from '$lib/icons/24/communication/CommentsNew.svelte';
import I20 from '$lib/icons/24/communication/Connect.svelte';
import I21 from '$lib/icons/24/communication/Contacts.svelte';
import I22 from '$lib/icons/24/communication/Forward.svelte';
import I23 from '$lib/icons/24/communication/ForwardFill.svelte';
import I24 from '$lib/icons/24/communication/Ghost.svelte';
import I25 from '$lib/icons/24/communication/Glassclock.svelte';
import I26 from '$lib/icons/24/communication/HandBreak.svelte';
import I27 from '$lib/icons/24/communication/History.svelte';
import I28 from '$lib/icons/24/communication/HistoryAction.svelte';
import I29 from '$lib/icons/24/communication/Incognito.svelte';
import I30 from '$lib/icons/24/communication/Lego.svelte';
import I31 from '$lib/icons/24/communication/Mail.svelte';
import I32 from '$lib/icons/24/communication/MailIncoming.svelte';
import I33 from '$lib/icons/24/communication/MailNew.svelte';
import I34 from '$lib/icons/24/communication/MailOpen.svelte';
import I35 from '$lib/icons/24/communication/MailOutgoing.svelte';
import I36 from '$lib/icons/24/communication/Message.svelte';
import I37 from '$lib/icons/24/communication/MessageNew.svelte';
import I38 from '$lib/icons/24/communication/OperatorSupport.svelte';
import I39 from '$lib/icons/24/communication/ParentIssue.svelte';
import I40 from '$lib/icons/24/communication/ParentIssueDocuments.svelte';
import I41 from '$lib/icons/24/communication/ParentIssueDouble.svelte';
import I42 from '$lib/icons/24/communication/ParentsControl.svelte';
import I43 from '$lib/icons/24/communication/PeopleWait.svelte';
import I44 from '$lib/icons/24/communication/PlaceWait.svelte';
import I45 from '$lib/icons/24/communication/Profile.svelte';
import I46 from '$lib/icons/24/communication/ProfileBusiness.svelte';
import I47 from '$lib/icons/24/communication/ProfileGoodman.svelte';
import I48 from '$lib/icons/24/communication/Puzzle.svelte';
import I49 from '$lib/icons/24/communication/Reply.svelte';
import I50 from '$lib/icons/24/communication/ReplyFill.svelte';
import I51 from '$lib/icons/24/communication/Share.svelte';
import I52 from '$lib/icons/24/communication/Target.svelte';
import I53 from '$lib/icons/24/communication/Task.svelte';
import I54 from '$lib/icons/24/communication/Unlimited.svelte';
import I55 from '$lib/icons/24/communication/User.svelte';
import I56 from '$lib/icons/24/communication/UserAdd.svelte';
import I57 from '$lib/icons/24/communication/UserMan.svelte';
import I58 from '$lib/icons/24/communication/UserNonBinary.svelte';
import I59 from '$lib/icons/24/communication/UserWoman.svelte';
import I60 from '$lib/icons/24/communication/UserWorker.svelte';
import I61 from '$lib/icons/24/communication/Users.svelte';

export default {
	"Aim": I0,
	"Alarm": I1,
	"Alien": I2,
	"At": I3,
	"Calendar": I4,
	"CalendarAdd": I5,
	"CalendarDelete": I6,
	"CalendarNumber": I7,
	"CalendarOpen": I8,
	"CalendarPeriod": I9,
	"Call": I10,
	"CallDialog": I11,
	"CallEnd": I12,
	"CallIncoming": I13,
	"CallNocoming": I14,
	"CallOutgoing": I15,
	"Chat": I16,
	"ChatNew": I17,
	"Comments": I18,
	"CommentsNew": I19,
	"Connect": I20,
	"Contacts": I21,
	"Forward": I22,
	"ForwardFill": I23,
	"Ghost": I24,
	"Glassclock": I25,
	"HandBreak": I26,
	"History": I27,
	"HistoryAction": I28,
	"Incognito": I29,
	"Lego": I30,
	"Mail": I31,
	"MailIncoming": I32,
	"MailNew": I33,
	"MailOpen": I34,
	"MailOutgoing": I35,
	"Message": I36,
	"MessageNew": I37,
	"OperatorSupport": I38,
	"ParentIssue": I39,
	"ParentIssueDocuments": I40,
	"ParentIssueDouble": I41,
	"ParentsControl": I42,
	"PeopleWait": I43,
	"PlaceWait": I44,
	"Profile": I45,
	"ProfileBusiness": I46,
	"ProfileGoodman": I47,
	"Puzzle": I48,
	"Reply": I49,
	"ReplyFill": I50,
	"Share": I51,
	"Target": I52,
	"Task": I53,
	"Unlimited": I54,
	"User": I55,
	"UserAdd": I56,
	"UserMan": I57,
	"UserNonBinary": I58,
	"UserWoman": I59,
	"UserWorker": I60,
	"Users": I61
};
