// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/document/index.js (order kept)
import I0 from '$lib/icons/24/document/AI.svelte';
import I1 from '$lib/icons/24/document/AIMonochrome.svelte';
import I2 from '$lib/icons/24/document/APP.svelte';
import I3 from '$lib/icons/24/document/APPMonochrome.svelte';
import I4 from '$lib/icons/24/document/Archive.svelte';
import I5 from '$lib/icons/24/document/ArchiveClosed.svelte';
import I6 from '$lib/icons/24/document/ArchiveColor.svelte';
import I7 from '$lib/icons/24/document/ArchiveImport.svelte';
import I8 from '$lib/icons/24/document/ArchiveMonochrome.svelte';
import I9 from '$lib/icons/24/document/CSS.svelte';
import I10 from '$lib/icons/24/document/CSSMonochrome.svelte';
import I11 from '$lib/icons/24/document/CSV.svelte';
import I12 from '$lib/icons/24/document/CSVMonochrome.svelte';
import I13 from '$lib/icons/24/document/DOC.svelte';
import I14 from '$lib/icons/24/document/DOCM.svelte';
import I15 from '$lib/icons/24/document/DOCMMonochrome.svelte';
import I16 from '$lib/icons/24/document/DOCMonochrome.svelte';
import I17 from '$lib/icons/24/document/DOCX.svelte';
import I18 from '$lib/icons/24/document/DOCXMonochrome.svelte';
import I19 from '$lib/icons/24/document/DOTX.svelte';
import I20 from '$lib/icons/24/document/DOTXMonochrome.svelte';
import I21 from '$lib/icons/24/document/DocumentAdd.svelte';
import I22 from '$lib/icons/24/document/DocumentArchived.svelte';
import I23 from '$lib/icons/24/document/DocumentCertificate.svelte';
import I24 from '$lib/icons/24/document/DocumentDownload.svelte';
import I25 from '$lib/icons/24/document/DocumentEdit.svelte';
import I26 from '$lib/icons/24/document/DocumentError.svelte';
import I27 from '$lib/icons/24/document/DocumentErrorColor.svelte';
import I28 from '$lib/icons/24/document/DocumentErrorMonochrome.svelte';
import I29 from '$lib/icons/24/document/DocumentImage.svelte';
import I30 from '$lib/icons/24/document/DocumentIncoming.svelte';
import I31 from '$lib/icons/24/document/DocumentOutgoing.svelte';
import I32 from '$lib/icons/24/document/DocumentRefresh.svelte';
import I33 from '$lib/icons/24/document/DocumentSearch.svelte';
import I34 from '$lib/icons/24/document/DocumentSecurity.svelte';
import I35 from '$lib/icons/24/document/DocumentSuccess.svelte';
import I36 from '$lib/icons/24/document/DocumentSuccessColor.svelte';
import I37 from '$lib/icons/24/document/DocumentSuccessMonochrome.svelte';
import I38 from '$lib/icons/24/document/DocumentText.svelte';
import I39 from '$lib/icons/24/document/DocumentUpload.svelte';
import I40 from '$lib/icons/24/document/EXE.svelte';
import I41 from '$lib/icons/24/document/EXEMonochrome.svelte';
import I42 from '$lib/icons/24/document/FIG.svelte';
import I43 from '$lib/icons/24/document/FIGMonochrome.svelte';
import I44 from '$lib/icons/24/document/File.svelte';
import I45 from '$lib/icons/24/document/FileColor.svelte';
import I46 from '$lib/icons/24/document/FileMonochrome.svelte';
import I47 from '$lib/icons/24/document/Folder.svelte';
import I48 from '$lib/icons/24/document/FolderAdd.svelte';
import I49 from '$lib/icons/24/document/FolderDetails.svelte';
import I50 from '$lib/icons/24/document/FolderFill.svelte';
import I51 from '$lib/icons/24/document/FolderMove.svelte';
import I52 from '$lib/icons/24/document/FolderOpen.svelte';
import I53 from '$lib/icons/24/document/FolderOpenFill.svelte';
import I54 from '$lib/icons/24/document/FolderShared.svelte';
import I55 from '$lib/icons/24/document/GIF.svelte';
import I56 from '$lib/icons/24/document/GIFMonochrome.svelte';
import I57 from '$lib/icons/24/document/HTML.svelte';
import I58 from '$lib/icons/24/document/HTMLMonochrome.svelte';
import I59 from '$lib/icons/24/document/ImageColor.svelte';
import I60 from '$lib/icons/24/document/ImageMonochrome.svelte';
import I61 from '$lib/icons/24/document/Infographics.svelte';
import I62 from '$lib/icons/24/document/InfographicsColor.svelte';
import I63 from '$lib/icons/24/document/InfographicsMonochrome.svelte';
import I64 from '$lib/icons/24/document/JFIF.svelte';
import I65 from '$lib/icons/24/document/JFIFMonochrome.svelte';
import I66 from '$lib/icons/24/document/JPG.svelte';
import I67 from '$lib/icons/24/document/JPGMonochrome.svelte';
import I68 from '$lib/icons/24/document/JS.svelte';
import I69 from '$lib/icons/24/document/JSMonochrome.svelte';
import I70 from '$lib/icons/24/document/JSON.svelte';
import I71 from '$lib/icons/24/document/JSONMonochrome.svelte';
import I72 from '$lib/icons/24/document/MBOX.svelte';
import I73 from '$lib/icons/24/document/MBOXMonochrome.svelte';
import I74 from '$lib/icons/24/document/MD.svelte';
import I75 from '$lib/icons/24/document/MDMonochrome.svelte';
import I76 from '$lib/icons/24/document/MP3.svelte';
import I77 from '$lib/icons/24/document/MP3Monochrome.svelte';
import I78 from '$lib/icons/24/document/MPEG.svelte';
import I79 from '$lib/icons/24/document/MPEGMonochrome.svelte';
import I80 from '$lib/icons/24/document/MPP.svelte';
import I81 from '$lib/icons/24/document/MPPMonochrome.svelte';
import I82 from '$lib/icons/24/document/MSG.svelte';
import I83 from '$lib/icons/24/document/MSGMonochrome.svelte';
import I84 from '$lib/icons/24/document/Media.svelte';
import I85 from '$lib/icons/24/document/MediaColor.svelte';
import I86 from '$lib/icons/24/document/MediaMonochrome.svelte';
import I87 from '$lib/icons/24/document/Music.svelte';
import I88 from '$lib/icons/24/document/MusicColor.svelte';
import I89 from '$lib/icons/24/document/MusicMonochrome.svelte';
import I90 from '$lib/icons/24/document/ODP.svelte';
import I91 from '$lib/icons/24/document/ODPMonochrome.svelte';
import I92 from '$lib/icons/24/document/ODS.svelte';
import I93 from '$lib/icons/24/document/ODSMonochrome.svelte';
import I94 from '$lib/icons/24/document/ODT.svelte';
import I95 from '$lib/icons/24/document/ODTMonochrome.svelte';
import I96 from '$lib/icons/24/document/PDF.svelte';
import I97 from '$lib/icons/24/document/PDFMonochrome.svelte';
import I98 from '$lib/icons/24/document/PNG.svelte';
import I99 from '$lib/icons/24/document/PNGMonochrome.svelte';
import I100 from '$lib/icons/24/document/PPT.svelte';
import I101 from '$lib/icons/24/document/PPTMonochrome.svelte';
import I102 from '$lib/icons/24/document/PPTX.svelte';
import I103 from '$lib/icons/24/document/PPTXMonochrome.svelte';
import I104 from '$lib/icons/24/document/PS.svelte';
import I105 from '$lib/icons/24/document/PSMonochrome.svelte';
import I106 from '$lib/icons/24/document/RAR.svelte';
import I107 from '$lib/icons/24/document/RARMonochrome.svelte';
import I108 from '$lib/icons/24/document/Reading.svelte';
import I109 from '$lib/icons/24/document/ReadingColor.svelte';
import I110 from '$lib/icons/24/document/ReadingMonochrome.svelte';
import I111 from '$lib/icons/24/document/SQL.svelte';
import I112 from '$lib/icons/24/document/SQLMonochrome.svelte';
import I113 from '$lib/icons/24/document/SVG.svelte';
import I114 from '$lib/icons/24/document/SVGMonochrome.svelte';
import I115 from '$lib/icons/24/document/Script.svelte';
import I116 from '$lib/icons/24/document/ScriptColor.svelte';
import I117 from '$lib/icons/24/document/ScriptMonochrome.svelte';
import I118 from '$lib/icons/24/document/SevenZIP.svelte';
import I119 from '$lib/icons/24/document/SevenZIPMonochrome.svelte';
import I120 from '$lib/icons/24/document/Snippet.svelte';
import I121 from '$lib/icons/24/document/SnippetColor.svelte';
import I122 from '$lib/icons/24/document/SnippetMonochrome.svelte';
import I123 from '$lib/icons/24/document/TIF.svelte';
import I124 from '$lib/icons/24/document/TIFF.svelte';
import I125 from '$lib/icons/24/document/TIFFMonochrome.svelte';
import I126 from '$lib/icons/24/document/TIFMonochrome.svelte';
import I127 from '$lib/icons/24/document/TXT.svelte';
import I128 from '$lib/icons/24/document/TXTMonochrome.svelte';
import I129 from '$lib/icons/24/document/Table.svelte';
import I130 from '$lib/icons/24/document/TableColor.svelte';
import I131 from '$lib/icons/24/document/TableMonochrome.svelte';
import I132 from '$lib/icons/24/document/TextColor.svelte';
import I133 from '$lib/icons/24/document/TextMonochrome.svelte';
import I134 from '$lib/icons/24/document/VSD.svelte';
import I135 from '$lib/icons/24/document/VSDMonochrome.svelte';
import I136 from '$lib/icons/24/document/VSDX.svelte';
import I137 from '$lib/icons/24/document/VSDXMonochrome.svelte';
import I138 from '$lib/icons/24/document/WAV.svelte';
import I139 from '$lib/icons/24/document/WAVMonochrome.svelte';
import I140 from '$lib/icons/24/document/WEBP.svelte';
import I141 from '$lib/icons/24/document/WEBPMonochrome.svelte';
import I142 from '$lib/icons/24/document/XD.svelte';
import I143 from '$lib/icons/24/document/XDMonochrome.svelte';
import I144 from '$lib/icons/24/document/XLS.svelte';
import I145 from '$lib/icons/24/document/XLSB.svelte';
import I146 from '$lib/icons/24/document/XLSBMonochrome.svelte';
import I147 from '$lib/icons/24/document/XLSM.svelte';
import I148 from '$lib/icons/24/document/XLSMMonochrome.svelte';
import I149 from '$lib/icons/24/document/XLSMonochrome.svelte';
import I150 from '$lib/icons/24/document/XLSX.svelte';
import I151 from '$lib/icons/24/document/XLSXMonochrome.svelte';
import I152 from '$lib/icons/24/document/ZIP.svelte';
import I153 from '$lib/icons/24/document/ZIPMonochrome.svelte';

export default {
	"AI": I0,
	"AIMonochrome": I1,
	"APP": I2,
	"APPMonochrome": I3,
	"Archive": I4,
	"ArchiveClosed": I5,
	"ArchiveColor": I6,
	"ArchiveImport": I7,
	"ArchiveMonochrome": I8,
	"CSS": I9,
	"CSSMonochrome": I10,
	"CSV": I11,
	"CSVMonochrome": I12,
	"DOC": I13,
	"DOCM": I14,
	"DOCMMonochrome": I15,
	"DOCMonochrome": I16,
	"DOCX": I17,
	"DOCXMonochrome": I18,
	"DOTX": I19,
	"DOTXMonochrome": I20,
	"DocumentAdd": I21,
	"DocumentArchived": I22,
	"DocumentCertificate": I23,
	"DocumentDownload": I24,
	"DocumentEdit": I25,
	"DocumentError": I26,
	"DocumentErrorColor": I27,
	"DocumentErrorMonochrome": I28,
	"DocumentImage": I29,
	"DocumentIncoming": I30,
	"DocumentOutgoing": I31,
	"DocumentRefresh": I32,
	"DocumentSearch": I33,
	"DocumentSecurity": I34,
	"DocumentSuccess": I35,
	"DocumentSuccessColor": I36,
	"DocumentSuccessMonochrome": I37,
	"DocumentText": I38,
	"DocumentUpload": I39,
	"EXE": I40,
	"EXEMonochrome": I41,
	"FIG": I42,
	"FIGMonochrome": I43,
	"File": I44,
	"FileColor": I45,
	"FileMonochrome": I46,
	"Folder": I47,
	"FolderAdd": I48,
	"FolderDetails": I49,
	"FolderFill": I50,
	"FolderMove": I51,
	"FolderOpen": I52,
	"FolderOpenFill": I53,
	"FolderShared": I54,
	"GIF": I55,
	"GIFMonochrome": I56,
	"HTML": I57,
	"HTMLMonochrome": I58,
	"ImageColor": I59,
	"ImageMonochrome": I60,
	"Infographics": I61,
	"InfographicsColor": I62,
	"InfographicsMonochrome": I63,
	"JFIF": I64,
	"JFIFMonochrome": I65,
	"JPG": I66,
	"JPGMonochrome": I67,
	"JS": I68,
	"JSMonochrome": I69,
	"JSON": I70,
	"JSONMonochrome": I71,
	"MBOX": I72,
	"MBOXMonochrome": I73,
	"MD": I74,
	"MDMonochrome": I75,
	"MP3": I76,
	"MP3Monochrome": I77,
	"MPEG": I78,
	"MPEGMonochrome": I79,
	"MPP": I80,
	"MPPMonochrome": I81,
	"MSG": I82,
	"MSGMonochrome": I83,
	"Media": I84,
	"MediaColor": I85,
	"MediaMonochrome": I86,
	"Music": I87,
	"MusicColor": I88,
	"MusicMonochrome": I89,
	"ODP": I90,
	"ODPMonochrome": I91,
	"ODS": I92,
	"ODSMonochrome": I93,
	"ODT": I94,
	"ODTMonochrome": I95,
	"PDF": I96,
	"PDFMonochrome": I97,
	"PNG": I98,
	"PNGMonochrome": I99,
	"PPT": I100,
	"PPTMonochrome": I101,
	"PPTX": I102,
	"PPTXMonochrome": I103,
	"PS": I104,
	"PSMonochrome": I105,
	"RAR": I106,
	"RARMonochrome": I107,
	"Reading": I108,
	"ReadingColor": I109,
	"ReadingMonochrome": I110,
	"SQL": I111,
	"SQLMonochrome": I112,
	"SVG": I113,
	"SVGMonochrome": I114,
	"Script": I115,
	"ScriptColor": I116,
	"ScriptMonochrome": I117,
	"SevenZIP": I118,
	"SevenZIPMonochrome": I119,
	"Snippet": I120,
	"SnippetColor": I121,
	"SnippetMonochrome": I122,
	"TIF": I123,
	"TIFF": I124,
	"TIFFMonochrome": I125,
	"TIFMonochrome": I126,
	"TXT": I127,
	"TXTMonochrome": I128,
	"Table": I129,
	"TableColor": I130,
	"TableMonochrome": I131,
	"TextColor": I132,
	"TextMonochrome": I133,
	"VSD": I134,
	"VSDMonochrome": I135,
	"VSDX": I136,
	"VSDXMonochrome": I137,
	"WAV": I138,
	"WAVMonochrome": I139,
	"WEBP": I140,
	"WEBPMonochrome": I141,
	"XD": I142,
	"XDMonochrome": I143,
	"XLS": I144,
	"XLSB": I145,
	"XLSBMonochrome": I146,
	"XLSM": I147,
	"XLSMMonochrome": I148,
	"XLSMonochrome": I149,
	"XLSX": I150,
	"XLSXMonochrome": I151,
	"ZIP": I152,
	"ZIPMonochrome": I153
};
