// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/editor/index.js (order kept)
import I0 from '$lib/icons/24/editor/Array.svelte';
import I1 from '$lib/icons/24/editor/Bullet.svelte';
import I2 from '$lib/icons/24/editor/CellsMerge.svelte';
import I3 from '$lib/icons/24/editor/Checkbox.svelte';
import I4 from '$lib/icons/24/editor/CheckboxGroup.svelte';
import I5 from '$lib/icons/24/editor/Code.svelte';
import I6 from '$lib/icons/24/editor/CodeBinary.svelte';
import I7 from '$lib/icons/24/editor/ColorPantone.svelte';
import I8 from '$lib/icons/24/editor/ColumnDelete.svelte';
import I9 from '$lib/icons/24/editor/ColumnLeft.svelte';
import I10 from '$lib/icons/24/editor/ColumnRight.svelte';
import I11 from '$lib/icons/24/editor/CompareAdd.svelte';
import I12 from '$lib/icons/24/editor/CompareAdded.svelte';
import I13 from '$lib/icons/24/editor/Crop.svelte';
import I14 from '$lib/icons/24/editor/DividerDot.svelte';
import I15 from '$lib/icons/24/editor/DividerHorizontal.svelte';
import I16 from '$lib/icons/24/editor/DividerVertical.svelte';
import I17 from '$lib/icons/24/editor/DragHorizontalDots.svelte';
import I18 from '$lib/icons/24/editor/DragHorizontalLines.svelte';
import I19 from '$lib/icons/24/editor/DragVerticalDots.svelte';
import I20 from '$lib/icons/24/editor/DragVerticalLines.svelte';
import I21 from '$lib/icons/24/editor/Edit.svelte';
import I22 from '$lib/icons/24/editor/En.svelte';
import I23 from '$lib/icons/24/editor/EndOfLine.svelte';
import I24 from '$lib/icons/24/editor/Equals.svelte';
import I25 from '$lib/icons/24/editor/Eraser.svelte';
import I26 from '$lib/icons/24/editor/Eyedropper.svelte';
import I27 from '$lib/icons/24/editor/EyedropperFill.svelte';
import I28 from '$lib/icons/24/editor/GridColumns1.svelte';
import I29 from '$lib/icons/24/editor/GridColumns2.svelte';
import I30 from '$lib/icons/24/editor/GridColumns3.svelte';
import I31 from '$lib/icons/24/editor/GridGant.svelte';
import I32 from '$lib/icons/24/editor/GridPanelLeft.svelte';
import I33 from '$lib/icons/24/editor/GridPanelRight.svelte';
import I34 from '$lib/icons/24/editor/GridTablet.svelte';
import I35 from '$lib/icons/24/editor/Hashtag.svelte';
import I36 from '$lib/icons/24/editor/Inputs.svelte';
import I37 from '$lib/icons/24/editor/LetterSpacing.svelte';
import I38 from '$lib/icons/24/editor/LineSpacing.svelte';
import I39 from '$lib/icons/24/editor/ListBulleted.svelte';
import I40 from '$lib/icons/24/editor/ListChecked.svelte';
import I41 from '$lib/icons/24/editor/ListNumbered.svelte';
import I42 from '$lib/icons/24/editor/ListUnchecked.svelte';
import I43 from '$lib/icons/24/editor/Marker.svelte';
import I44 from '$lib/icons/24/editor/MarketingFunnel.svelte';
import I45 from '$lib/icons/24/editor/MiddleOfLine.svelte';
import I46 from '$lib/icons/24/editor/Monospace.svelte';
import I47 from '$lib/icons/24/editor/NullAdd.svelte';
import I48 from '$lib/icons/24/editor/NullDelete.svelte';
import I49 from '$lib/icons/24/editor/Numbers.svelte';
import I50 from '$lib/icons/24/editor/ObjectAlignBottomVertical.svelte';
import I51 from '$lib/icons/24/editor/ObjectAlignCenterHorizontal.svelte';
import I52 from '$lib/icons/24/editor/ObjectAlignCenterVertical.svelte';
import I53 from '$lib/icons/24/editor/ObjectAlignDistanceHorizontal.svelte';
import I54 from '$lib/icons/24/editor/ObjectAlignDistanceVertical.svelte';
import I55 from '$lib/icons/24/editor/ObjectAlignDividerHorizontal.svelte';
import I56 from '$lib/icons/24/editor/ObjectAlignDividerVertical.svelte';
import I57 from '$lib/icons/24/editor/ObjectAlignLeftHorizontal.svelte';
import I58 from '$lib/icons/24/editor/ObjectAlignRightHorizontal.svelte';
import I59 from '$lib/icons/24/editor/ObjectAlignTopVertical.svelte';
import I60 from '$lib/icons/24/editor/Objects.svelte';
import I61 from '$lib/icons/24/editor/PaintBucket.svelte';
import I62 from '$lib/icons/24/editor/PaintBucketFill.svelte';
import I63 from '$lib/icons/24/editor/Pen.svelte';
import I64 from '$lib/icons/24/editor/PenTool.svelte';
import I65 from '$lib/icons/24/editor/Pencil.svelte';
import I66 from '$lib/icons/24/editor/Plumage.svelte';
import I67 from '$lib/icons/24/editor/Quote.svelte';
import I68 from '$lib/icons/24/editor/Radiobutton.svelte';
import I69 from '$lib/icons/24/editor/Rename.svelte';
import I70 from '$lib/icons/24/editor/Rotate3D.svelte';
import I71 from '$lib/icons/24/editor/RowAbove.svelte';
import I72 from '$lib/icons/24/editor/RowBelow.svelte';
import I73 from '$lib/icons/24/editor/RowDelete.svelte';
import I74 from '$lib/icons/24/editor/Ru.svelte';
import I75 from '$lib/icons/24/editor/Scissors.svelte';
import I76 from '$lib/icons/24/editor/Separator.svelte';
import I77 from '$lib/icons/24/editor/Sigma.svelte';
import I78 from '$lib/icons/24/editor/SortDown.svelte';
import I79 from '$lib/icons/24/editor/SortUp.svelte';
import I80 from '$lib/icons/24/editor/StartOfLine.svelte';
import I81 from '$lib/icons/24/editor/Terminal.svelte';
import I82 from '$lib/icons/24/editor/Text.svelte';
import I83 from '$lib/icons/24/editor/TextAlignCenter.svelte';
import I84 from '$lib/icons/24/editor/TextAlignDistance.svelte';
import I85 from '$lib/icons/24/editor/TextAlignLeft.svelte';
import I86 from '$lib/icons/24/editor/TextAlignRight.svelte';
import I87 from '$lib/icons/24/editor/TextBold.svelte';
import I88 from '$lib/icons/24/editor/TextCapsLock.svelte';
import I89 from '$lib/icons/24/editor/TextItalic.svelte';
import I90 from '$lib/icons/24/editor/TextLower.svelte';
import I91 from '$lib/icons/24/editor/TextRise.svelte';
import I92 from '$lib/icons/24/editor/TextSearch.svelte';
import I93 from '$lib/icons/24/editor/TextStrikethrough.svelte';
import I94 from '$lib/icons/24/editor/TextSubscript.svelte';
import I95 from '$lib/icons/24/editor/TextSuperscript.svelte';
import I96 from '$lib/icons/24/editor/TextUnderline.svelte';
import I97 from '$lib/icons/24/editor/Translate.svelte';
import I98 from '$lib/icons/24/editor/Value.svelte';

export default {
	"Array": I0,
	"Bullet": I1,
	"CellsMerge": I2,
	"Checkbox": I3,
	"CheckboxGroup": I4,
	"Code": I5,
	"CodeBinary": I6,
	"ColorPantone": I7,
	"ColumnDelete": I8,
	"ColumnLeft": I9,
	"ColumnRight": I10,
	"CompareAdd": I11,
	"CompareAdded": I12,
	"Crop": I13,
	"DividerDot": I14,
	"DividerHorizontal": I15,
	"DividerVertical": I16,
	"DragHorizontalDots": I17,
	"DragHorizontalLines": I18,
	"DragVerticalDots": I19,
	"DragVerticalLines": I20,
	"Edit": I21,
	"En": I22,
	"EndOfLine": I23,
	"Equals": I24,
	"Eraser": I25,
	"Eyedropper": I26,
	"EyedropperFill": I27,
	"GridColumns1": I28,
	"GridColumns2": I29,
	"GridColumns3": I30,
	"GridGant": I31,
	"GridPanelLeft": I32,
	"GridPanelRight": I33,
	"GridTablet": I34,
	"Hashtag": I35,
	"Inputs": I36,
	"LetterSpacing": I37,
	"LineSpacing": I38,
	"ListBulleted": I39,
	"ListChecked": I40,
	"ListNumbered": I41,
	"ListUnchecked": I42,
	"Marker": I43,
	"MarketingFunnel": I44,
	"MiddleOfLine": I45,
	"Monospace": I46,
	"NullAdd": I47,
	"NullDelete": I48,
	"Numbers": I49,
	"ObjectAlignBottomVertical": I50,
	"ObjectAlignCenterHorizontal": I51,
	"ObjectAlignCenterVertical": I52,
	"ObjectAlignDistanceHorizontal": I53,
	"ObjectAlignDistanceVertical": I54,
	"ObjectAlignDividerHorizontal": I55,
	"ObjectAlignDividerVertical": I56,
	"ObjectAlignLeftHorizontal": I57,
	"ObjectAlignRightHorizontal": I58,
	"ObjectAlignTopVertical": I59,
	"Objects": I60,
	"PaintBucket": I61,
	"PaintBucketFill": I62,
	"Pen": I63,
	"PenTool": I64,
	"Pencil": I65,
	"Plumage": I66,
	"Quote": I67,
	"Radiobutton": I68,
	"Rename": I69,
	"Rotate3D": I70,
	"RowAbove": I71,
	"RowBelow": I72,
	"RowDelete": I73,
	"Ru": I74,
	"Scissors": I75,
	"Separator": I76,
	"Sigma": I77,
	"SortDown": I78,
	"SortUp": I79,
	"StartOfLine": I80,
	"Terminal": I81,
	"Text": I82,
	"TextAlignCenter": I83,
	"TextAlignDistance": I84,
	"TextAlignLeft": I85,
	"TextAlignRight": I86,
	"TextBold": I87,
	"TextCapsLock": I88,
	"TextItalic": I89,
	"TextLower": I90,
	"TextRise": I91,
	"TextSearch": I92,
	"TextStrikethrough": I93,
	"TextSubscript": I94,
	"TextSuperscript": I95,
	"TextUnderline": I96,
	"Translate": I97,
	"Value": I98
};
