// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/logo/index.js (order kept)
import I0 from '$lib/icons/24/logo/Android.svelte';
import I1 from '$lib/icons/24/logo/AndroidFill.svelte';
import I2 from '$lib/icons/24/logo/Apple.svelte';
import I3 from '$lib/icons/24/logo/AppleFill.svelte';
import I4 from '$lib/icons/24/logo/DrWeb.svelte';
import I5 from '$lib/icons/24/logo/EsetNod.svelte';
import I6 from '$lib/icons/24/logo/Flickr.svelte';
import I7 from '$lib/icons/24/logo/FlickrFill.svelte';
import I8 from '$lib/icons/24/logo/Flutter.svelte';
import I9 from '$lib/icons/24/logo/FlutterFill.svelte';
import I10 from '$lib/icons/24/logo/FourGame.svelte';
import I11 from '$lib/icons/24/logo/Github.svelte';
import I12 from '$lib/icons/24/logo/GithubFill.svelte';
import I13 from '$lib/icons/24/logo/Gitlab.svelte';
import I14 from '$lib/icons/24/logo/GitlabFill.svelte';
import I15 from '$lib/icons/24/logo/GooglePlay.svelte';
import I16 from '$lib/icons/24/logo/GooglePlayFill.svelte';
import I17 from '$lib/icons/24/logo/Googleplus.svelte';
import I18 from '$lib/icons/24/logo/Gosuslugi.svelte';
import I19 from '$lib/icons/24/logo/Kluch.svelte';
import I20 from '$lib/icons/24/logo/KluchFill.svelte';
import I21 from '$lib/icons/24/logo/Licey.svelte';
import I22 from '$lib/icons/24/logo/LiceyFill.svelte';
import I23 from '$lib/icons/24/logo/MYGAMES.svelte';
import I24 from '$lib/icons/24/logo/Mailru.svelte';
import I25 from '$lib/icons/24/logo/Max.svelte';
import I26 from '$lib/icons/24/logo/MicrosoftOffice.svelte';
import I27 from '$lib/icons/24/logo/Odnoklassniki.svelte';
import I28 from '$lib/icons/24/logo/OdnoklassnikiFill.svelte';
import I29 from '$lib/icons/24/logo/Onlime.svelte';
import I30 from '$lib/icons/24/logo/OnlimeFill.svelte';
import I31 from '$lib/icons/24/logo/Rostelecom.svelte';
import I32 from '$lib/icons/24/logo/RostelecomFill.svelte';
import I33 from '$lib/icons/24/logo/RostelecomSmartHome.svelte';
import I34 from '$lib/icons/24/logo/RostelecomSmartHomeFill.svelte';
import I35 from '$lib/icons/24/logo/Sber.svelte';
import I36 from '$lib/icons/24/logo/TamTam.svelte';
import I37 from '$lib/icons/24/logo/Telegram.svelte';
import I38 from '$lib/icons/24/logo/TelegramFill.svelte';
import I39 from '$lib/icons/24/logo/Twitter.svelte';
import I40 from '$lib/icons/24/logo/TwitterFill.svelte';
import I41 from '$lib/icons/24/logo/Viber.svelte';
import I42 from '$lib/icons/24/logo/Vkontakte.svelte';
import I43 from '$lib/icons/24/logo/VkontakteFill.svelte';
import I44 from '$lib/icons/24/logo/Wargaming.svelte';
import I45 from '$lib/icons/24/logo/WhatsApp.svelte';
import I46 from '$lib/icons/24/logo/Windows.svelte';
import I47 from '$lib/icons/24/logo/WindowsFill.svelte';
import I48 from '$lib/icons/24/logo/Wink.svelte';
import I49 from '$lib/icons/24/logo/WinkFill.svelte';
import I50 from '$lib/icons/24/logo/Yandex.svelte';
import I51 from '$lib/icons/24/logo/YandexDisk.svelte';
import I52 from '$lib/icons/24/logo/YandexDiskFill.svelte';
import I53 from '$lib/icons/24/logo/YandexFill.svelte';
import I54 from '$lib/icons/24/logo/Youtube.svelte';
import I55 from '$lib/icons/24/logo/YoutubeFill.svelte';

export default {
	"Android": I0,
	"AndroidFill": I1,
	"Apple": I2,
	"AppleFill": I3,
	"DrWeb": I4,
	"EsetNod": I5,
	"Flickr": I6,
	"FlickrFill": I7,
	"Flutter": I8,
	"FlutterFill": I9,
	"FourGame": I10,
	"Github": I11,
	"GithubFill": I12,
	"Gitlab": I13,
	"GitlabFill": I14,
	"GooglePlay": I15,
	"GooglePlayFill": I16,
	"Googleplus": I17,
	"Gosuslugi": I18,
	"Kluch": I19,
	"KluchFill": I20,
	"Licey": I21,
	"LiceyFill": I22,
	"MYGAMES": I23,
	"Mailru": I24,
	"Max": I25,
	"MicrosoftOffice": I26,
	"Odnoklassniki": I27,
	"OdnoklassnikiFill": I28,
	"Onlime": I29,
	"OnlimeFill": I30,
	"Rostelecom": I31,
	"RostelecomFill": I32,
	"RostelecomSmartHome": I33,
	"RostelecomSmartHomeFill": I34,
	"Sber": I35,
	"TamTam": I36,
	"Telegram": I37,
	"TelegramFill": I38,
	"Twitter": I39,
	"TwitterFill": I40,
	"Viber": I41,
	"Vkontakte": I42,
	"VkontakteFill": I43,
	"Wargaming": I44,
	"WhatsApp": I45,
	"Windows": I46,
	"WindowsFill": I47,
	"Wink": I48,
	"WinkFill": I49,
	"Yandex": I50,
	"YandexDisk": I51,
	"YandexDiskFill": I52,
	"YandexFill": I53,
	"Youtube": I54,
	"YoutubeFill": I55
};
