// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/media/index.js (order kept)
import I0 from '$lib/icons/24/media/Camera.svelte';
import I1 from '$lib/icons/24/media/CameraFill.svelte';
import I2 from '$lib/icons/24/media/CameraOff.svelte';
import I3 from '$lib/icons/24/media/CameraOffFill.svelte';
import I4 from '$lib/icons/24/media/FastForward.svelte';
import I5 from '$lib/icons/24/media/FastForward10s.svelte';
import I6 from '$lib/icons/24/media/FastForward15s.svelte';
import I7 from '$lib/icons/24/media/FastForward30s.svelte';
import I8 from '$lib/icons/24/media/FastForward5s.svelte';
import I9 from '$lib/icons/24/media/FastRewind.svelte';
import I10 from '$lib/icons/24/media/FastRewind10s.svelte';
import I11 from '$lib/icons/24/media/FastRewind15s.svelte';
import I12 from '$lib/icons/24/media/FastRewind30s.svelte';
import I13 from '$lib/icons/24/media/FastRewind5s.svelte';
import I14 from '$lib/icons/24/media/Focus3D.svelte';
import I15 from '$lib/icons/24/media/FocusAR.svelte';
import I16 from '$lib/icons/24/media/FocusRecords.svelte';
import I17 from '$lib/icons/24/media/FocusVR.svelte';
import I18 from '$lib/icons/24/media/GalleryHorizontal.svelte';
import I19 from '$lib/icons/24/media/GalleryVertical.svelte';
import I20 from '$lib/icons/24/media/Headphones.svelte';
import I21 from '$lib/icons/24/media/Image.svelte';
import I22 from '$lib/icons/24/media/Live.svelte';
import I23 from '$lib/icons/24/media/Maximize.svelte';
import I24 from '$lib/icons/24/media/Megaphone.svelte';
import I25 from '$lib/icons/24/media/Melody.svelte';
import I26 from '$lib/icons/24/media/MelodyTone.svelte';
import I27 from '$lib/icons/24/media/Microphone.svelte';
import I28 from '$lib/icons/24/media/MicrophoneFill.svelte';
import I29 from '$lib/icons/24/media/MicrophoneMute.svelte';
import I30 from '$lib/icons/24/media/MicrophoneMuteFill.svelte';
import I31 from '$lib/icons/24/media/MicrophoneTalker.svelte';
import I32 from '$lib/icons/24/media/Minimize.svelte';
import I33 from '$lib/icons/24/media/Overview1Screen.svelte';
import I34 from '$lib/icons/24/media/Overview2Screen.svelte';
import I35 from '$lib/icons/24/media/Overview4Screen.svelte';
import I36 from '$lib/icons/24/media/Overview6Screen.svelte';
import I37 from '$lib/icons/24/media/PackContent.svelte';
import I38 from '$lib/icons/24/media/PackTV.svelte';
import I39 from '$lib/icons/24/media/Pause.svelte';
import I40 from '$lib/icons/24/media/PauseFill.svelte';
import I41 from '$lib/icons/24/media/PauseObject.svelte';
import I42 from '$lib/icons/24/media/Photo.svelte';
import I43 from '$lib/icons/24/media/Play.svelte';
import I44 from '$lib/icons/24/media/PlayFill.svelte';
import I45 from '$lib/icons/24/media/PlayNext.svelte';
import I46 from '$lib/icons/24/media/PlayObject.svelte';
import I47 from '$lib/icons/24/media/PlayPrevious.svelte';
import I48 from '$lib/icons/24/media/Screen4K.svelte';
import I49 from '$lib/icons/24/media/ScreenControl.svelte';
import I50 from '$lib/icons/24/media/ScreenHD.svelte';
import I51 from '$lib/icons/24/media/ScreenSettings.svelte';
import I52 from '$lib/icons/24/media/ScreenSubscription.svelte';
import I53 from '$lib/icons/24/media/ScreenTV.svelte';
import I54 from '$lib/icons/24/media/Speed1x.svelte';
import I55 from '$lib/icons/24/media/Speed2x.svelte';
import I56 from '$lib/icons/24/media/Speed4x.svelte';
import I57 from '$lib/icons/24/media/Speed6x.svelte';
import I58 from '$lib/icons/24/media/Speed8x.svelte';
import I59 from '$lib/icons/24/media/SpeedPlayback.svelte';
import I60 from '$lib/icons/24/media/Stop.svelte';
import I61 from '$lib/icons/24/media/StopFill.svelte';
import I62 from '$lib/icons/24/media/StopObject.svelte';
import I63 from '$lib/icons/24/media/Subtitles.svelte';
import I64 from '$lib/icons/24/media/SubtitlesFill.svelte';
import I65 from '$lib/icons/24/media/Translation.svelte';
import I66 from '$lib/icons/24/media/Voice.svelte';
import I67 from '$lib/icons/24/media/VolumeDown.svelte';
import I68 from '$lib/icons/24/media/VolumeDownFill.svelte';
import I69 from '$lib/icons/24/media/VolumeOff.svelte';
import I70 from '$lib/icons/24/media/VolumeOffFill.svelte';
import I71 from '$lib/icons/24/media/VolumeUp.svelte';
import I72 from '$lib/icons/24/media/VolumeUpFill.svelte';
import I73 from '$lib/icons/24/media/ZoomIn.svelte';
import I74 from '$lib/icons/24/media/ZoomOut.svelte';

export default {
	"Camera": I0,
	"CameraFill": I1,
	"CameraOff": I2,
	"CameraOffFill": I3,
	"FastForward": I4,
	"FastForward10s": I5,
	"FastForward15s": I6,
	"FastForward30s": I7,
	"FastForward5s": I8,
	"FastRewind": I9,
	"FastRewind10s": I10,
	"FastRewind15s": I11,
	"FastRewind30s": I12,
	"FastRewind5s": I13,
	"Focus3D": I14,
	"FocusAR": I15,
	"FocusRecords": I16,
	"FocusVR": I17,
	"GalleryHorizontal": I18,
	"GalleryVertical": I19,
	"Headphones": I20,
	"Image": I21,
	"Live": I22,
	"Maximize": I23,
	"Megaphone": I24,
	"Melody": I25,
	"MelodyTone": I26,
	"Microphone": I27,
	"MicrophoneFill": I28,
	"MicrophoneMute": I29,
	"MicrophoneMuteFill": I30,
	"MicrophoneTalker": I31,
	"Minimize": I32,
	"Overview1Screen": I33,
	"Overview2Screen": I34,
	"Overview4Screen": I35,
	"Overview6Screen": I36,
	"PackContent": I37,
	"PackTV": I38,
	"Pause": I39,
	"PauseFill": I40,
	"PauseObject": I41,
	"Photo": I42,
	"Play": I43,
	"PlayFill": I44,
	"PlayNext": I45,
	"PlayObject": I46,
	"PlayPrevious": I47,
	"Screen4K": I48,
	"ScreenControl": I49,
	"ScreenHD": I50,
	"ScreenSettings": I51,
	"ScreenSubscription": I52,
	"ScreenTV": I53,
	"Speed1x": I54,
	"Speed2x": I55,
	"Speed4x": I56,
	"Speed6x": I57,
	"Speed8x": I58,
	"SpeedPlayback": I59,
	"Stop": I60,
	"StopFill": I61,
	"StopObject": I62,
	"Subtitles": I63,
	"SubtitlesFill": I64,
	"Translation": I65,
	"Voice": I66,
	"VolumeDown": I67,
	"VolumeDownFill": I68,
	"VolumeOff": I69,
	"VolumeOffFill": I70,
	"VolumeUp": I71,
	"VolumeUpFill": I72,
	"ZoomIn": I73,
	"ZoomOut": I74
};
