// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/navigation/index.js (order kept)
import I0 from '$lib/icons/24/navigation/ArrowDown.svelte';
import I1 from '$lib/icons/24/navigation/ArrowForwardLeft.svelte';
import I2 from '$lib/icons/24/navigation/ArrowForwardRight.svelte';
import I3 from '$lib/icons/24/navigation/ArrowLeft.svelte';
import I4 from '$lib/icons/24/navigation/ArrowLeftDown.svelte';
import I5 from '$lib/icons/24/navigation/ArrowLeftUp.svelte';
import I6 from '$lib/icons/24/navigation/ArrowRight.svelte';
import I7 from '$lib/icons/24/navigation/ArrowRightDown.svelte';
import I8 from '$lib/icons/24/navigation/ArrowRightLeft.svelte';
import I9 from '$lib/icons/24/navigation/ArrowRightUp.svelte';
import I10 from '$lib/icons/24/navigation/ArrowUp.svelte';
import I11 from '$lib/icons/24/navigation/ArrowUpDown.svelte';
import I12 from '$lib/icons/24/navigation/CaretSort.svelte';
import I13 from '$lib/icons/24/navigation/CaretSortDown.svelte';
import I14 from '$lib/icons/24/navigation/CaretSortUp.svelte';
import I15 from '$lib/icons/24/navigation/CheckLarge.svelte';
import I16 from '$lib/icons/24/navigation/CheckLargeDouble.svelte';
import I17 from '$lib/icons/24/navigation/CheckSmall.svelte';
import I18 from '$lib/icons/24/navigation/ChevronDown.svelte';
import I19 from '$lib/icons/24/navigation/ChevronLeft.svelte';
import I20 from '$lib/icons/24/navigation/ChevronRight.svelte';
import I21 from '$lib/icons/24/navigation/ChevronSort.svelte';
import I22 from '$lib/icons/24/navigation/ChevronUp.svelte';
import I23 from '$lib/icons/24/navigation/CloseLarge.svelte';
import I24 from '$lib/icons/24/navigation/CloseSmall.svelte';
import I25 from '$lib/icons/24/navigation/Flag.svelte';
import I26 from '$lib/icons/24/navigation/FlagMini.svelte';
import I27 from '$lib/icons/24/navigation/Fold.svelte';
import I28 from '$lib/icons/24/navigation/Geolocation.svelte';
import I29 from '$lib/icons/24/navigation/GeolocationFill.svelte';
import I30 from '$lib/icons/24/navigation/LinkNative.svelte';
import I31 from '$lib/icons/24/navigation/Map.svelte';
import I32 from '$lib/icons/24/navigation/Menu.svelte';
import I33 from '$lib/icons/24/navigation/MenuCatalog.svelte';
import I34 from '$lib/icons/24/navigation/MenuFuture.svelte';
import I35 from '$lib/icons/24/navigation/MenuFutureKebab.svelte';
import I36 from '$lib/icons/24/navigation/MenuFuturePlusBullets.svelte';
import I37 from '$lib/icons/24/navigation/MenuKebab.svelte';
import I38 from '$lib/icons/24/navigation/MenuPlusBullets.svelte';
import I39 from '$lib/icons/24/navigation/More.svelte';
import I40 from '$lib/icons/24/navigation/Navigation.svelte';
import I41 from '$lib/icons/24/navigation/Next.svelte';
import I42 from '$lib/icons/24/navigation/Pin.svelte';
import I43 from '$lib/icons/24/navigation/PinFill.svelte';
import I44 from '$lib/icons/24/navigation/Previous.svelte';
import I45 from '$lib/icons/24/navigation/Redo.svelte';
import I46 from '$lib/icons/24/navigation/SearchEmpty.svelte';
import I47 from '$lib/icons/24/navigation/SearchMinus.svelte';
import I48 from '$lib/icons/24/navigation/SearchPlus.svelte';
import I49 from '$lib/icons/24/navigation/SignIn.svelte';
import I50 from '$lib/icons/24/navigation/SignOut.svelte';
import I51 from '$lib/icons/24/navigation/TreeForwardLeft.svelte';
import I52 from '$lib/icons/24/navigation/TreeForwardRight.svelte';
import I53 from '$lib/icons/24/navigation/Undo.svelte';
import I54 from '$lib/icons/24/navigation/Unfold.svelte';

export default {
	"ArrowDown": I0,
	"ArrowForwardLeft": I1,
	"ArrowForwardRight": I2,
	"ArrowLeft": I3,
	"ArrowLeftDown": I4,
	"ArrowLeftUp": I5,
	"ArrowRight": I6,
	"ArrowRightDown": I7,
	"ArrowRightLeft": I8,
	"ArrowRightUp": I9,
	"ArrowUp": I10,
	"ArrowUpDown": I11,
	"CaretSort": I12,
	"CaretSortDown": I13,
	"CaretSortUp": I14,
	"CheckLarge": I15,
	"CheckLargeDouble": I16,
	"CheckSmall": I17,
	"ChevronDown": I18,
	"ChevronLeft": I19,
	"ChevronRight": I20,
	"ChevronSort": I21,
	"ChevronUp": I22,
	"CloseLarge": I23,
	"CloseSmall": I24,
	"Flag": I25,
	"FlagMini": I26,
	"Fold": I27,
	"Geolocation": I28,
	"GeolocationFill": I29,
	"LinkNative": I30,
	"Map": I31,
	"Menu": I32,
	"MenuCatalog": I33,
	"MenuFuture": I34,
	"MenuFutureKebab": I35,
	"MenuFuturePlusBullets": I36,
	"MenuKebab": I37,
	"MenuPlusBullets": I38,
	"More": I39,
	"Navigation": I40,
	"Next": I41,
	"Pin": I42,
	"PinFill": I43,
	"Previous": I44,
	"Redo": I45,
	"SearchEmpty": I46,
	"SearchMinus": I47,
	"SearchPlus": I48,
	"SignIn": I49,
	"SignOut": I50,
	"TreeForwardLeft": I51,
	"TreeForwardRight": I52,
	"Undo": I53,
	"Unfold": I54
};
