// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/place/index.js (order kept)
import I0 from '$lib/icons/24/place/Administration.svelte';
import I1 from '$lib/icons/24/place/Anchor.svelte';
import I2 from '$lib/icons/24/place/Armchair.svelte';
import I3 from '$lib/icons/24/place/Backyard.svelte';
import I4 from '$lib/icons/24/place/BackyardTree.svelte';
import I5 from '$lib/icons/24/place/Balloon.svelte';
import I6 from '$lib/icons/24/place/Barbeque.svelte';
import I7 from '$lib/icons/24/place/Bed.svelte';
import I8 from '$lib/icons/24/place/Breaking.svelte';
import I9 from '$lib/icons/24/place/Broom.svelte';
import I10 from '$lib/icons/24/place/BrushRepair.svelte';
import I11 from '$lib/icons/24/place/Bus.svelte';
import I12 from '$lib/icons/24/place/Car.svelte';
import I13 from '$lib/icons/24/place/ChristmasTree.svelte';
import I14 from '$lib/icons/24/place/City.svelte';
import I15 from '$lib/icons/24/place/Cleaver.svelte';
import I16 from '$lib/icons/24/place/Clothes.svelte';
import I17 from '$lib/icons/24/place/Cloud.svelte';
import I18 from '$lib/icons/24/place/CoffeeBreak.svelte';
import I19 from '$lib/icons/24/place/Cookie.svelte';
import I20 from '$lib/icons/24/place/Cyclist.svelte';
import I21 from '$lib/icons/24/place/DarkTheme.svelte';
import I22 from '$lib/icons/24/place/DarkThemeFill.svelte';
import I23 from '$lib/icons/24/place/DeliveryBus.svelte';
import I24 from '$lib/icons/24/place/DeliveryCar.svelte';
import I25 from '$lib/icons/24/place/Disability.svelte';
import I26 from '$lib/icons/24/place/Door.svelte';
import I27 from '$lib/icons/24/place/DoorExit.svelte';
import I28 from '$lib/icons/24/place/Drop.svelte';
import I29 from '$lib/icons/24/place/Duck.svelte';
import I30 from '$lib/icons/24/place/Dumbbell.svelte';
import I31 from '$lib/icons/24/place/Earth.svelte';
import I32 from '$lib/icons/24/place/Escalator.svelte';
import I33 from '$lib/icons/24/place/EscalatorDown.svelte';
import I34 from '$lib/icons/24/place/EscalatorUp.svelte';
import I35 from '$lib/icons/24/place/Factory.svelte';
import I36 from '$lib/icons/24/place/FigureFamily.svelte';
import I37 from '$lib/icons/24/place/FigureMan.svelte';
import I38 from '$lib/icons/24/place/FigureManWoman.svelte';
import I39 from '$lib/icons/24/place/FigureWoman.svelte';
import I40 from '$lib/icons/24/place/Fire.svelte';
import I41 from '$lib/icons/24/place/Food.svelte';
import I42 from '$lib/icons/24/place/ForkKnife.svelte';
import I43 from '$lib/icons/24/place/ForkSpoon.svelte';
import I44 from '$lib/icons/24/place/Hammer.svelte';
import I45 from '$lib/icons/24/place/HammerAndWrench.svelte';
import I46 from '$lib/icons/24/place/Helicopter.svelte';
import I47 from '$lib/icons/24/place/Horse.svelte';
import I48 from '$lib/icons/24/place/Kettlebell.svelte';
import I49 from '$lib/icons/24/place/Kite.svelte';
import I50 from '$lib/icons/24/place/Knife.svelte';
import I51 from '$lib/icons/24/place/Kremlin.svelte';
import I52 from '$lib/icons/24/place/Launch.svelte';
import I53 from '$lib/icons/24/place/Lifebuoy.svelte';
import I54 from '$lib/icons/24/place/Lift.svelte';
import I55 from '$lib/icons/24/place/Metro.svelte';
import I56 from '$lib/icons/24/place/Monument.svelte';
import I57 from '$lib/icons/24/place/Moon.svelte';
import I58 from '$lib/icons/24/place/Motorbike.svelte';
import I59 from '$lib/icons/24/place/Office.svelte';
import I60 from '$lib/icons/24/place/Officechair.svelte';
import I61 from '$lib/icons/24/place/Pacifier.svelte';
import I62 from '$lib/icons/24/place/Pass.svelte';
import I63 from '$lib/icons/24/place/Plane.svelte';
import I64 from '$lib/icons/24/place/Radar.svelte';
import I65 from '$lib/icons/24/place/Realty.svelte';
import I66 from '$lib/icons/24/place/Roller.svelte';
import I67 from '$lib/icons/24/place/RulerAndPencil.svelte';
import I68 from '$lib/icons/24/place/Saturn.svelte';
import I69 from '$lib/icons/24/place/Saw.svelte';
import I70 from '$lib/icons/24/place/Screwdriver.svelte';
import I71 from '$lib/icons/24/place/Ship.svelte';
import I72 from '$lib/icons/24/place/Smoking.svelte';
import I73 from '$lib/icons/24/place/Snowflake.svelte';
import I74 from '$lib/icons/24/place/SosAlarm.svelte';
import I75 from '$lib/icons/24/place/Stairs.svelte';
import I76 from '$lib/icons/24/place/Stroller.svelte';
import I77 from '$lib/icons/24/place/Sun.svelte';
import I78 from '$lib/icons/24/place/Sweet.svelte';
import I79 from '$lib/icons/24/place/Tank.svelte';
import I80 from '$lib/icons/24/place/TestSpeed.svelte';
import I81 from '$lib/icons/24/place/Thermometer.svelte';
import I82 from '$lib/icons/24/place/Train.svelte';
import I83 from '$lib/icons/24/place/Tray.svelte';
import I84 from '$lib/icons/24/place/Tribune.svelte';
import I85 from '$lib/icons/24/place/Umbrella.svelte';
import I86 from '$lib/icons/24/place/UmbrellaBeach.svelte';
import I87 from '$lib/icons/24/place/VacationBeach.svelte';
import I88 from '$lib/icons/24/place/VacationSea.svelte';
import I89 from '$lib/icons/24/place/Wrench.svelte';

export default {
	"Administration": I0,
	"Anchor": I1,
	"Armchair": I2,
	"Backyard": I3,
	"BackyardTree": I4,
	"Balloon": I5,
	"Barbeque": I6,
	"Bed": I7,
	"Breaking": I8,
	"Broom": I9,
	"BrushRepair": I10,
	"Bus": I11,
	"Car": I12,
	"ChristmasTree": I13,
	"City": I14,
	"Cleaver": I15,
	"Clothes": I16,
	"Cloud": I17,
	"CoffeeBreak": I18,
	"Cookie": I19,
	"Cyclist": I20,
	"DarkTheme": I21,
	"DarkThemeFill": I22,
	"DeliveryBus": I23,
	"DeliveryCar": I24,
	"Disability": I25,
	"Door": I26,
	"DoorExit": I27,
	"Drop": I28,
	"Duck": I29,
	"Dumbbell": I30,
	"Earth": I31,
	"Escalator": I32,
	"EscalatorDown": I33,
	"EscalatorUp": I34,
	"Factory": I35,
	"FigureFamily": I36,
	"FigureMan": I37,
	"FigureManWoman": I38,
	"FigureWoman": I39,
	"Fire": I40,
	"Food": I41,
	"ForkKnife": I42,
	"ForkSpoon": I43,
	"Hammer": I44,
	"HammerAndWrench": I45,
	"Helicopter": I46,
	"Horse": I47,
	"Kettlebell": I48,
	"Kite": I49,
	"Knife": I50,
	"Kremlin": I51,
	"Launch": I52,
	"Lifebuoy": I53,
	"Lift": I54,
	"Metro": I55,
	"Monument": I56,
	"Moon": I57,
	"Motorbike": I58,
	"Office": I59,
	"Officechair": I60,
	"Pacifier": I61,
	"Pass": I62,
	"Plane": I63,
	"Radar": I64,
	"Realty": I65,
	"Roller": I66,
	"RulerAndPencil": I67,
	"Saturn": I68,
	"Saw": I69,
	"Screwdriver": I70,
	"Ship": I71,
	"Smoking": I72,
	"Snowflake": I73,
	"SosAlarm": I74,
	"Stairs": I75,
	"Stroller": I76,
	"Sun": I77,
	"Sweet": I78,
	"Tank": I79,
	"TestSpeed": I80,
	"Thermometer": I81,
	"Train": I82,
	"Tray": I83,
	"Tribune": I84,
	"Umbrella": I85,
	"UmbrellaBeach": I86,
	"VacationBeach": I87,
	"VacationSea": I88,
	"Wrench": I89
};
