// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/rating/index.js (order kept)
import I0 from '$lib/icons/24/rating/Dislike.svelte';
import I1 from '$lib/icons/24/rating/DislikeFill.svelte';
import I2 from '$lib/icons/24/rating/FaceFrowning.svelte';
import I3 from '$lib/icons/24/rating/FaceFrowningColor.svelte';
import I4 from '$lib/icons/24/rating/FaceGrin.svelte';
import I5 from '$lib/icons/24/rating/FaceGrinColor.svelte';
import I6 from '$lib/icons/24/rating/FaceNeutral.svelte';
import I7 from '$lib/icons/24/rating/FaceNeutralColor.svelte';
import I8 from '$lib/icons/24/rating/FaceOpenMouth.svelte';
import I9 from '$lib/icons/24/rating/FaceOpenMouthColor.svelte';
import I10 from '$lib/icons/24/rating/FaceRage.svelte';
import I11 from '$lib/icons/24/rating/FaceRageColor.svelte';
import I12 from '$lib/icons/24/rating/FaceSmilling.svelte';
import I13 from '$lib/icons/24/rating/FaceSmillingColor.svelte';
import I14 from '$lib/icons/24/rating/Favorite.svelte';
import I15 from '$lib/icons/24/rating/FavoriteFill.svelte';
import I16 from '$lib/icons/24/rating/Heart.svelte';
import I17 from '$lib/icons/24/rating/HeartBroken.svelte';
import I18 from '$lib/icons/24/rating/HeartFill.svelte';
import I19 from '$lib/icons/24/rating/Like.svelte';
import I20 from '$lib/icons/24/rating/LikeFill.svelte';
import I21 from '$lib/icons/24/rating/PriorityHigh.svelte';
import I22 from '$lib/icons/24/rating/PriorityHighFill.svelte';
import I23 from '$lib/icons/24/rating/PriorityLow.svelte';
import I24 from '$lib/icons/24/rating/PriorityLowFill.svelte';
import I25 from '$lib/icons/24/rating/PriorityNegativeLow.svelte';
import I26 from '$lib/icons/24/rating/PriorityNegativeLowFill.svelte';
import I27 from '$lib/icons/24/rating/PriorityNegativeNormal.svelte';
import I28 from '$lib/icons/24/rating/PriorityNegativeNormalFill.svelte';
import I29 from '$lib/icons/24/rating/PriorityNormal.svelte';
import I30 from '$lib/icons/24/rating/PriorityNormalFill.svelte';
import I31 from '$lib/icons/24/rating/PriorityVeryHigh.svelte';
import I32 from '$lib/icons/24/rating/PriorityVeryHighFill.svelte';
import I33 from '$lib/icons/24/rating/Rating.svelte';
import I34 from '$lib/icons/24/rating/RatingFill.svelte';
import I35 from '$lib/icons/24/rating/RatingHalf.svelte';
import I36 from '$lib/icons/24/rating/RatingNo.svelte';

export default {
	"Dislike": I0,
	"DislikeFill": I1,
	"FaceFrowning": I2,
	"FaceFrowningColor": I3,
	"FaceGrin": I4,
	"FaceGrinColor": I5,
	"FaceNeutral": I6,
	"FaceNeutralColor": I7,
	"FaceOpenMouth": I8,
	"FaceOpenMouthColor": I9,
	"FaceRage": I10,
	"FaceRageColor": I11,
	"FaceSmilling": I12,
	"FaceSmillingColor": I13,
	"Favorite": I14,
	"FavoriteFill": I15,
	"Heart": I16,
	"HeartBroken": I17,
	"HeartFill": I18,
	"Like": I19,
	"LikeFill": I20,
	"PriorityHigh": I21,
	"PriorityHighFill": I22,
	"PriorityLow": I23,
	"PriorityLowFill": I24,
	"PriorityNegativeLow": I25,
	"PriorityNegativeLowFill": I26,
	"PriorityNegativeNormal": I27,
	"PriorityNegativeNormalFill": I28,
	"PriorityNormal": I29,
	"PriorityNormalFill": I30,
	"PriorityVeryHigh": I31,
	"PriorityVeryHighFill": I32,
	"Rating": I33,
	"RatingFill": I34,
	"RatingHalf": I35,
	"RatingNo": I36
};
