// GENERATED by tools/gen-icons-full.mjs - webpack namespace object of packages/icons/dist/24/technology/index.js (order kept)
import I0 from '$lib/icons/24/technology/AdapterPCL.svelte';
import I1 from '$lib/icons/24/technology/Adaptive.svelte';
import I2 from '$lib/icons/24/technology/AllDevices.svelte';
import I3 from '$lib/icons/24/technology/Atom.svelte';
import I4 from '$lib/icons/24/technology/Barrier.svelte';
import I5 from '$lib/icons/24/technology/BatteryChargeEmpty.svelte';
import I6 from '$lib/icons/24/technology/BatteryChargeHalh.svelte';
import I7 from '$lib/icons/24/technology/BatteryEmpty.svelte';
import I8 from '$lib/icons/24/technology/BatteryFill.svelte';
import I9 from '$lib/icons/24/technology/Bluetooth.svelte';
import I10 from '$lib/icons/24/technology/BluetoothOff.svelte';
import I11 from '$lib/icons/24/technology/Broadcast.svelte';
import I12 from '$lib/icons/24/technology/BroadcastOff.svelte';
import I13 from '$lib/icons/24/technology/CameraCeiling.svelte';
import I14 from '$lib/icons/24/technology/CameraHome.svelte';
import I15 from '$lib/icons/24/technology/CameraHomeGroup.svelte';
import I16 from '$lib/icons/24/technology/CameraStreet.svelte';
import I17 from '$lib/icons/24/technology/CloudDatastore.svelte';
import I18 from '$lib/icons/24/technology/CloudGame.svelte';
import I19 from '$lib/icons/24/technology/CloudNetwork.svelte';
import I20 from '$lib/icons/24/technology/CloudServer.svelte';
import I21 from '$lib/icons/24/technology/Console.svelte';
import I22 from '$lib/icons/24/technology/Controller.svelte';
import I23 from '$lib/icons/24/technology/Counter.svelte';
import I24 from '$lib/icons/24/technology/Datastore.svelte';
import I25 from '$lib/icons/24/technology/Debug.svelte';
import I26 from '$lib/icons/24/technology/Desktop.svelte';
import I27 from '$lib/icons/24/technology/DesktopAdd.svelte';
import I28 from '$lib/icons/24/technology/Device.svelte';
import I29 from '$lib/icons/24/technology/DeviceWifi.svelte';
import I30 from '$lib/icons/24/technology/Equipment.svelte';
import I31 from '$lib/icons/24/technology/Fax.svelte';
import I32 from '$lib/icons/24/technology/FlashCard.svelte';
import I33 from '$lib/icons/24/technology/Flashlight.svelte';
import I34 from '$lib/icons/24/technology/FloppyDisk.svelte';
import I35 from '$lib/icons/24/technology/Game.svelte';
import I36 from '$lib/icons/24/technology/Intercom.svelte';
import I37 from '$lib/icons/24/technology/Internet.svelte';
import I38 from '$lib/icons/24/technology/InternetAdd.svelte';
import I39 from '$lib/icons/24/technology/InternetCableOne.svelte';
import I40 from '$lib/icons/24/technology/InternetCableThree.svelte';
import I41 from '$lib/icons/24/technology/InternetWifi.svelte';
import I42 from '$lib/icons/24/technology/Keyboard.svelte';
import I43 from '$lib/icons/24/technology/LandlinePhone.svelte';
import I44 from '$lib/icons/24/technology/Laptop.svelte';
import I45 from '$lib/icons/24/technology/LightBulb.svelte';
import I46 from '$lib/icons/24/technology/Magic.svelte';
import I47 from '$lib/icons/24/technology/MagicFill.svelte';
import I48 from '$lib/icons/24/technology/MagicWand.svelte';
import I49 from '$lib/icons/24/technology/Microchip.svelte';
import I50 from '$lib/icons/24/technology/Microcircuit.svelte';
import I51 from '$lib/icons/24/technology/Mobile.svelte';
import I52 from '$lib/icons/24/technology/MobileAdd.svelte';
import I53 from '$lib/icons/24/technology/MobileInfo.svelte';
import I54 from '$lib/icons/24/technology/MobileInternet.svelte';
import I55 from '$lib/icons/24/technology/MobileRefresh.svelte';
import I56 from '$lib/icons/24/technology/MobileSignal.svelte';
import I57 from '$lib/icons/24/technology/Modem.svelte';
import I58 from '$lib/icons/24/technology/OtherService.svelte';
import I59 from '$lib/icons/24/technology/Phone.svelte';
import I60 from '$lib/icons/24/technology/PhoneAdd.svelte';
import I61 from '$lib/icons/24/technology/PhoneInternet.svelte';
import I62 from '$lib/icons/24/technology/PhoneRoaming.svelte';
import I63 from '$lib/icons/24/technology/PhoneTime.svelte';
import I64 from '$lib/icons/24/technology/ProgramLoad.svelte';
import I65 from '$lib/icons/24/technology/Radio.svelte';
import I66 from '$lib/icons/24/technology/Registrator.svelte';
import I67 from '$lib/icons/24/technology/Robot.svelte';
import I68 from '$lib/icons/24/technology/SIM.svelte';
import I69 from '$lib/icons/24/technology/ScreenCableThree.svelte';
import I70 from '$lib/icons/24/technology/ScreenInternet.svelte';
import I71 from '$lib/icons/24/technology/Server.svelte';
import I72 from '$lib/icons/24/technology/ServerNetwork.svelte';
import I73 from '$lib/icons/24/technology/Servers.svelte';
import I74 from '$lib/icons/24/technology/SetOfMinutes.svelte';
import I75 from '$lib/icons/24/technology/Signaling.svelte';
import I76 from '$lib/icons/24/technology/SmartHome.svelte';
import I77 from '$lib/icons/24/technology/SmartHomeAdd.svelte';
import I78 from '$lib/icons/24/technology/Socket.svelte';
import I79 from '$lib/icons/24/technology/Station.svelte';
import I80 from '$lib/icons/24/technology/Stopwatch.svelte';
import I81 from '$lib/icons/24/technology/Subnet.svelte';
import I82 from '$lib/icons/24/technology/Tablet.svelte';
import I83 from '$lib/icons/24/technology/ThermalImager.svelte';
import I84 from '$lib/icons/24/technology/UnknownDevice.svelte';
import I85 from '$lib/icons/24/technology/VRHelmet.svelte';
import I86 from '$lib/icons/24/technology/VRMask.svelte';
import I87 from '$lib/icons/24/technology/Wifi.svelte';
import I88 from '$lib/icons/24/technology/WifiDisconnect.svelte';
import I89 from '$lib/icons/24/technology/WifiOff.svelte';

export default {
	"AdapterPCL": I0,
	"Adaptive": I1,
	"AllDevices": I2,
	"Atom": I3,
	"Barrier": I4,
	"BatteryChargeEmpty": I5,
	"BatteryChargeHalh": I6,
	"BatteryEmpty": I7,
	"BatteryFill": I8,
	"Bluetooth": I9,
	"BluetoothOff": I10,
	"Broadcast": I11,
	"BroadcastOff": I12,
	"CameraCeiling": I13,
	"CameraHome": I14,
	"CameraHomeGroup": I15,
	"CameraStreet": I16,
	"CloudDatastore": I17,
	"CloudGame": I18,
	"CloudNetwork": I19,
	"CloudServer": I20,
	"Console": I21,
	"Controller": I22,
	"Counter": I23,
	"Datastore": I24,
	"Debug": I25,
	"Desktop": I26,
	"DesktopAdd": I27,
	"Device": I28,
	"DeviceWifi": I29,
	"Equipment": I30,
	"Fax": I31,
	"FlashCard": I32,
	"Flashlight": I33,
	"FloppyDisk": I34,
	"Game": I35,
	"Intercom": I36,
	"Internet": I37,
	"InternetAdd": I38,
	"InternetCableOne": I39,
	"InternetCableThree": I40,
	"InternetWifi": I41,
	"Keyboard": I42,
	"LandlinePhone": I43,
	"Laptop": I44,
	"LightBulb": I45,
	"Magic": I46,
	"MagicFill": I47,
	"MagicWand": I48,
	"Microchip": I49,
	"Microcircuit": I50,
	"Mobile": I51,
	"MobileAdd": I52,
	"MobileInfo": I53,
	"MobileInternet": I54,
	"MobileRefresh": I55,
	"MobileSignal": I56,
	"Modem": I57,
	"OtherService": I58,
	"Phone": I59,
	"PhoneAdd": I60,
	"PhoneInternet": I61,
	"PhoneRoaming": I62,
	"PhoneTime": I63,
	"ProgramLoad": I64,
	"Radio": I65,
	"Registrator": I66,
	"Robot": I67,
	"SIM": I68,
	"ScreenCableThree": I69,
	"ScreenInternet": I70,
	"Server": I71,
	"ServerNetwork": I72,
	"Servers": I73,
	"SetOfMinutes": I74,
	"Signaling": I75,
	"SmartHome": I76,
	"SmartHomeAdd": I77,
	"Socket": I78,
	"Station": I79,
	"Stopwatch": I80,
	"Subnet": I81,
	"Tablet": I82,
	"ThermalImager": I83,
	"UnknownDevice": I84,
	"VRHelmet": I85,
	"VRMask": I86,
	"Wifi": I87,
	"WifiDisconnect": I88,
	"WifiOff": I89
};
