// Generate src/lib/index.ts from the component tree so parallel authors never touch a shared file.
//   src/lib/components/**/<Name>.svelte  -> export { default as <Name> } from ...
//   src/lib/components/**/*.ts           -> export * from ...   (only files named index.ts / types.ts / *.util.ts are skipped)
// Conflicting names are prefixed with their parent directory.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lib = path.join(root, 'src/lib');
const comps = path.join(lib, 'components');

function* walk(d) {
  if (!fs.existsSync(d)) return;
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) yield* walk(p); else yield p;
  }
}

const svelte = [...walk(comps)].filter((f) => f.endsWith('.svelte') && !path.basename(f).startsWith('_')).sort();
const names = {};
for (const f of svelte) (names[path.basename(f, '.svelte')] ??= []).push(f);

const lines = ["export * from './constants.js';", "export * from './icons/index.js';"];
for (const [name, files] of Object.entries(names)) {
  for (const f of files) {
    const rel = './' + path.relative(lib, f).replace(/\\/g, '/');
    const exported = files.length > 1 ? path.basename(path.dirname(f)) + name : name;
    lines.push(`export { default as ${exported} } from '${rel}';`);
  }
}
// Component folders that ship their own public entry (today: TableGrid/index.ts -> useSelection, filter/sort constants, types).
// The explicit `export { default as X }` lines above win over anything re-exported by these `export *` lines.
for (const f of [...walk(comps)].filter((f) => path.basename(f) === 'index.ts').sort()) {
  lines.push(`export * from './${path.relative(lib, f).replace(/\\/g, '/').replace(/\.ts$/, '.js')}';`);
}
for (const dir of ['hooks', 'utils', 'actions']) {
  const idx = path.join(lib, dir, 'index.ts');
  if (fs.existsSync(idx)) lines.push(`export * from './${dir}/index.js';`);
}
fs.writeFileSync(path.join(lib, 'index.ts'), '// GENERATED by tools/gen-barrel.mjs — do not edit\n' + lines.join('\n') + '\n');
console.log(`barrel: ${svelte.length} components, ${Object.values(names).filter((f) => f.length > 1).length} name clashes`);
